/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Tue Oct 30 20:39:58 2018. */

#include "AlarmClock.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t AlarmClockItem_fields[8] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, AlarmClockItem, id, id, 0),
    PB_FIELD(  2, BOOL    , REQUIRED, STATIC  , OTHER, AlarmClockItem, enable, id, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, AlarmClockItem, hour, enable, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, AlarmClockItem, minute, hour, 0),
    PB_FIELD(  5, STRING  , REQUIRED, STATIC  , OTHER, AlarmClockItem, tag, minute, 0),
    PB_FIELD(  6, UENUM   , REPEATED, STATIC  , OTHER, AlarmClockItem, repeats, tag, 0),
    PB_FIELD(  7, INT32   , OPTIONAL, STATIC  , OTHER, AlarmClockItem, snoozeMode, repeats, 0),
    PB_LAST_FIELD
};

const pb_field_t AlarmClockList_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, AlarmClockList, items, items, &AlarmClockItem_fields),
    PB_LAST_FIELD
};

const pb_field_t AlarmClockDeleteItem_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, AlarmClockDeleteItem, id, id, 0),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(AlarmClockList, items[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_AlarmClockItem_AlarmClockList_AlarmClockDeleteItem)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(AlarmClockList, items[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_AlarmClockItem_AlarmClockList_AlarmClockDeleteItem)
#endif


/* @@protoc_insertion_point(eof) */
