/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Tue Oct 30 20:39:58 2018. */

#ifndef PB_ALARMCLOCK_PB_H_INCLUDED
#define PB_ALARMCLOCK_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _AlarmClockItem_RepeatType {
    AlarmClockItem_RepeatType_NEVER = 0,
    AlarmClockItem_RepeatType_MONDAY = 1,
    AlarmClockItem_RepeatType_TUESDAY = 2,
    AlarmClockItem_RepeatType_WEDNESDAY = 3,
    AlarmClockItem_RepeatType_THURSDAY = 4,
    AlarmClockItem_RepeatType_FRIDAY = 5,
    AlarmClockItem_RepeatType_SATURDAY = 6,
    AlarmClockItem_RepeatType_SUNDAY = 7,
    AlarmClockItem_RepeatType_WORKDAY = 8
} AlarmClockItem_RepeatType;
#define _AlarmClockItem_RepeatType_MIN AlarmClockItem_RepeatType_NEVER
#define _AlarmClockItem_RepeatType_MAX AlarmClockItem_RepeatType_WORKDAY
#define _AlarmClockItem_RepeatType_ARRAYSIZE ((AlarmClockItem_RepeatType)(AlarmClockItem_RepeatType_WORKDAY+1))

/* Struct definitions */
typedef struct _AlarmClockDeleteItem {
    int32_t id;
/* @@protoc_insertion_point(struct:AlarmClockDeleteItem) */
} AlarmClockDeleteItem;

typedef struct _AlarmClockItem {
    int32_t id;
    bool enable;
    int32_t hour;
    int32_t minute;
    char tag[25];
    pb_size_t repeats_count;
    AlarmClockItem_RepeatType repeats[9];
    bool has_snoozeMode;
    int32_t snoozeMode;
/* @@protoc_insertion_point(struct:AlarmClockItem) */
} AlarmClockItem;

typedef struct _AlarmClockList {
    pb_size_t items_count;
    AlarmClockItem items[10];
/* @@protoc_insertion_point(struct:AlarmClockList) */
} AlarmClockList;

/* Default values for struct fields */

/* Initializer values for message structs */
#define AlarmClockItem_init_default              {0, 0, 0, 0, "", 0, {(AlarmClockItem_RepeatType)0, (AlarmClockItem_RepeatType)0, (AlarmClockItem_RepeatType)0, (AlarmClockItem_RepeatType)0, (AlarmClockItem_RepeatType)0, (AlarmClockItem_RepeatType)0, (AlarmClockItem_RepeatType)0, (AlarmClockItem_RepeatType)0, (AlarmClockItem_RepeatType)0}, false, 0}
#define AlarmClockList_init_default              {0, {AlarmClockItem_init_default, AlarmClockItem_init_default, AlarmClockItem_init_default, AlarmClockItem_init_default, AlarmClockItem_init_default, AlarmClockItem_init_default, AlarmClockItem_init_default, AlarmClockItem_init_default, AlarmClockItem_init_default, AlarmClockItem_init_default}}
#define AlarmClockDeleteItem_init_default        {0}
#define AlarmClockItem_init_zero                 {0, 0, 0, 0, "", 0, {(AlarmClockItem_RepeatType)0, (AlarmClockItem_RepeatType)0, (AlarmClockItem_RepeatType)0, (AlarmClockItem_RepeatType)0, (AlarmClockItem_RepeatType)0, (AlarmClockItem_RepeatType)0, (AlarmClockItem_RepeatType)0, (AlarmClockItem_RepeatType)0, (AlarmClockItem_RepeatType)0}, false, 0}
#define AlarmClockList_init_zero                 {0, {AlarmClockItem_init_zero, AlarmClockItem_init_zero, AlarmClockItem_init_zero, AlarmClockItem_init_zero, AlarmClockItem_init_zero, AlarmClockItem_init_zero, AlarmClockItem_init_zero, AlarmClockItem_init_zero, AlarmClockItem_init_zero, AlarmClockItem_init_zero}}
#define AlarmClockDeleteItem_init_zero           {0}

/* Field tags (for use in manual encoding/decoding) */
#define AlarmClockDeleteItem_id_tag              1
#define AlarmClockItem_id_tag                    1
#define AlarmClockItem_enable_tag                2
#define AlarmClockItem_hour_tag                  3
#define AlarmClockItem_minute_tag                4
#define AlarmClockItem_tag_tag                   5
#define AlarmClockItem_repeats_tag               6
#define AlarmClockItem_snoozeMode_tag            7
#define AlarmClockList_items_tag                 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t AlarmClockItem_fields[8];
extern const pb_field_t AlarmClockList_fields[2];
extern const pb_field_t AlarmClockDeleteItem_fields[2];

/* Maximum encoded size of messages (where known) */
#define AlarmClockItem_size                      91
#define AlarmClockList_size                      930    // 465 when was 5 count
#define AlarmClockDeleteItem_size                11

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ALARMCLOCK_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
