/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Mon Nov 12 20:14:00 2018. */

#ifndef PB_BODYSTATUS_PB_H_INCLUDED
#define PB_BODYSTATUS_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _HeartRateRecord_MeasureType {
    HeartRateRecord_MeasureType_MANUAL = 0,
    HeartRateRecord_MeasureType_AUTO = 1
} HeartRateRecord_MeasureType;
#define _HeartRateRecord_MeasureType_MIN HeartRateRecord_MeasureType_MANUAL
#define _HeartRateRecord_MeasureType_MAX HeartRateRecord_MeasureType_AUTO
#define _HeartRateRecord_MeasureType_ARRAYSIZE ((HeartRateRecord_MeasureType)(HeartRateRecord_MeasureType_AUTO+1))

typedef enum _BodyStatusRecord_Type {
    BodyStatusRecord_Type_SLEEP = 0,
    BodyStatusRecord_Type_REST = 1,
    BodyStatusRecord_Type_LITE_ACTIVITY = 2,
    BodyStatusRecord_Type_STEP = 3,
    BodyStatusRecord_Type_BRISK_WALK = 4,
    BodyStatusRecord_Type_STAIR = 5,
    BodyStatusRecord_Type_RUN = 6,
    BodyStatusRecord_Type_RIDE = 7,
    BodyStatusRecord_Type_SWIM = 8,
    BodyStatusRecord_Type_SLEEP_LITE = 9,
    BodyStatusRecord_Type_INDOOR_RIDE = 10,
    BodyStatusRecord_Type_INDOOR_RUN = 11,
    BodyStatusRecord_Type_OUTDOOR_WALK = 12,
    BodyStatusRecord_Type_FREE = 13,
    BodyStatusRecord_Type_OUTDOOR_RIDE = 14,
    BodyStatusRecord_Type_INDOOR_SWIM = 15
} BodyStatusRecord_Type;
#define _BodyStatusRecord_Type_MIN BodyStatusRecord_Type_SLEEP
#define _BodyStatusRecord_Type_MAX BodyStatusRecord_Type_INDOOR_SWIM
#define _BodyStatusRecord_Type_ARRAYSIZE ((BodyStatusRecord_Type)(BodyStatusRecord_Type_INDOOR_SWIM+1))

/* Struct definitions */
typedef struct _FreeTrainingStatusRecord_Point {
    int64_t time;
    int32_t step;
    int32_t heart_rate;
    int32_t calorie;
/* @@protoc_insertion_point(struct:FreeTrainingStatusRecord_Point) */
} FreeTrainingStatusRecord_Point;

typedef struct _HeartRateRecord {
    int32_t rate;
    int64_t time;
    HeartRateRecord_MeasureType measure_type;
    bool is_resting;
/* @@protoc_insertion_point(struct:HeartRateRecord) */
} HeartRateRecord;

typedef struct _IndoorBikeStatusRecord_Point {
    int64_t time;
    int32_t step;
    int32_t heart_rate;
    int32_t calorie;
/* @@protoc_insertion_point(struct:IndoorBikeStatusRecord_Point) */
} IndoorBikeStatusRecord_Point;

typedef struct _IndoorRunStatusRecord_Point {
    int64_t time;
    int32_t step;
    int32_t heart_rate;
    int32_t calorie;
    bool has_distance;
    float distance;
    int32_t step_freq;
/* @@protoc_insertion_point(struct:IndoorRunStatusRecord_Point) */
} IndoorRunStatusRecord_Point;

typedef struct _IndoorSwimmingStatusRecord_Point {
    int64_t time;
    int32_t step;
    int32_t heart_rate;
    int32_t calorie;
    float distance;
    int32_t strokes_cnt;
    int32_t swolf;
    bool has_SwimmingPosture;
    int32_t SwimmingPosture;
/* @@protoc_insertion_point(struct:IndoorSwimmingStatusRecord_Point) */
} IndoorSwimmingStatusRecord_Point;

typedef struct _OutdoorBikeStatusRecord_Point {
    int64_t time;
    int32_t step;
    int32_t heart_rate;
    int32_t calorie;
    bool has_longitude;
    double longitude;
    bool has_latitude;
    double latitude;
    bool has_distance;
    float distance;
    bool has_gps_status;
    bool gps_status;
/* @@protoc_insertion_point(struct:OutdoorBikeStatusRecord_Point) */
} OutdoorBikeStatusRecord_Point;

typedef struct _OutdoorWalkStatusRecord_Point {
    int64_t time;
    int32_t step;
    int32_t heart_rate;
    int32_t calorie;
    bool has_longitude;
    double longitude;
    bool has_latitude;
    double latitude;
    bool has_distance;
    float distance;
    bool has_gps_status;
    bool gps_status;
/* @@protoc_insertion_point(struct:OutdoorWalkStatusRecord_Point) */
} OutdoorWalkStatusRecord_Point;

typedef struct _RunStatusRecord_Point {
    int64_t time;
    int32_t step;
    int32_t heart_rate;
    int32_t calorie;
    bool has_longitude;
    double longitude;
    bool has_latitude;
    double latitude;
    bool has_distance;
    float distance;
    bool has_gps_status;
    bool gps_status;
/* @@protoc_insertion_point(struct:RunStatusRecord_Point) */
} RunStatusRecord_Point;

typedef struct _CommonRecord {
    int64_t start_time;
    int64_t end_time;
    pb_size_t heart_rates_count;
    HeartRateRecord heart_rates[5];
    bool has_calorie;
    int32_t calorie;
    bool has_distance;
    int32_t distance;
    bool has_long_sit;
    int32_t long_sit;
    int32_t session_id;
    int32_t total;
    int32_t sn;
    bool has_deviation;
    int32_t deviation;
    bool has_daylight;
    int32_t daylight;	
/* @@protoc_insertion_point(struct:CommonRecord) */
} CommonRecord;

typedef struct _BriskWalkStatusRecord {
    CommonRecord common;
    int32_t step;
/* @@protoc_insertion_point(struct:BriskWalkStatusRecord) */
} BriskWalkStatusRecord;

typedef struct _FreeTrainingStatusRecord {
    CommonRecord common;
    pb_size_t point_count;
    FreeTrainingStatusRecord_Point point[5];
/* @@protoc_insertion_point(struct:FreeTrainingStatusRecord) */
} FreeTrainingStatusRecord;

typedef struct _IndoorBikeStatusRecord {
    CommonRecord common;
    pb_size_t point_count;
    IndoorBikeStatusRecord_Point point[5];
/* @@protoc_insertion_point(struct:IndoorBikeStatusRecord) */
} IndoorBikeStatusRecord;

typedef struct _IndoorRunStatusRecord {
    CommonRecord common;
    pb_size_t point_count;
    IndoorRunStatusRecord_Point point[5];
/* @@protoc_insertion_point(struct:IndoorRunStatusRecord) */
} IndoorRunStatusRecord;

typedef struct _IndoorSwimmingStatusRecord {
    CommonRecord common;
    pb_size_t point_count;
    IndoorSwimmingStatusRecord_Point point[5];
/* @@protoc_insertion_point(struct:IndoorSwimmingStatusRecord) */
} IndoorSwimmingStatusRecord;

typedef struct _LiteActivityStatusRecord {
    CommonRecord common;
    int32_t step;
/* @@protoc_insertion_point(struct:LiteActivityStatusRecord) */
} LiteActivityStatusRecord;

typedef struct _OutdoorBikeStatusRecord {
    CommonRecord common;
    pb_size_t point_count;
    OutdoorBikeStatusRecord_Point point[5];
/* @@protoc_insertion_point(struct:OutdoorBikeStatusRecord) */
} OutdoorBikeStatusRecord;

typedef struct _OutdoorWalkStatusRecord {
    CommonRecord common;
    pb_size_t point_count;
    OutdoorWalkStatusRecord_Point point[5];
/* @@protoc_insertion_point(struct:OutdoorWalkStatusRecord) */
} OutdoorWalkStatusRecord;

typedef struct _RestStatusRecord {
    CommonRecord common;
    int32_t step;
/* @@protoc_insertion_point(struct:RestStatusRecord) */
} RestStatusRecord;

typedef struct _RideStatusRecord {
    CommonRecord common;
/* @@protoc_insertion_point(struct:RideStatusRecord) */
} RideStatusRecord;

typedef struct _RunStatusRecord {
    CommonRecord common;
    pb_size_t point_count;
    RunStatusRecord_Point point[5];
/* @@protoc_insertion_point(struct:RunStatusRecord) */
} RunStatusRecord;

typedef struct _SleepLiteStatusRecord {
    CommonRecord common;
    int32_t version;
    int32_t type;
    uint32_t step;
/* @@protoc_insertion_point(struct:SleepLiteStatusRecord) */
} SleepLiteStatusRecord;

typedef struct _SleepStatusRecord {
    CommonRecord common;
    int32_t version;
    pb_size_t rris_count;
    uint32_t rris[90];
    uint32_t step;
/* @@protoc_insertion_point(struct:SleepStatusRecord) */
} SleepStatusRecord;

typedef struct _StairStatusRecord {
    CommonRecord common;
    int32_t step;
/* @@protoc_insertion_point(struct:StairStatusRecord) */
} StairStatusRecord;

typedef struct _StepStatusRecord {
    CommonRecord common;
    int32_t step;
    int32_t freq;
/* @@protoc_insertion_point(struct:StepStatusRecord) */
} StepStatusRecord;

typedef struct _SwimStatusRecord {
    CommonRecord common;
/* @@protoc_insertion_point(struct:SwimStatusRecord) */
} SwimStatusRecord;

typedef struct _BodyStatusRecord {
    BodyStatusRecord_Type type;
    pb_size_t which_message;
    union {
        RestStatusRecord rest;
        LiteActivityStatusRecord lite_activity;
        StepStatusRecord step;
        BriskWalkStatusRecord brisk_walk;
        StairStatusRecord stair;
        RunStatusRecord run;
        RideStatusRecord ride;
        SwimStatusRecord swim;
        SleepLiteStatusRecord sleep_lite;
        OutdoorWalkStatusRecord outdoor_walk;
        IndoorRunStatusRecord indoor_run;
        IndoorBikeStatusRecord indoor_ride;
        FreeTrainingStatusRecord free;
        OutdoorBikeStatusRecord outdoor_ride;
        IndoorSwimmingStatusRecord indoor_swim;
    } message;
    bool has_today_step;
    int32_t today_step;
/* @@protoc_insertion_point(struct:BodyStatusRecord) */
} BodyStatusRecord;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HeartRateRecord_init_default             {0, 0, (HeartRateRecord_MeasureType)0, 0}
//#define CommonRecord_init_default                {0, 0, 0, {HeartRateRecord_init_default, HeartRateRecord_init_default, HeartRateRecord_init_default, HeartRateRecord_init_default, HeartRateRecord_init_default}, false, 0, false, 0, false, 0, 0, 0, 0}
#define CommonRecord_init_default                {0, 0, 0, {HeartRateRecord_init_default, HeartRateRecord_init_default, HeartRateRecord_init_default, HeartRateRecord_init_default, HeartRateRecord_init_default}, false, 0, false, 0, false, 0, 0, 0, 0, false, 0, false, 0}
#define BodyStatusRecord_init_default            {(BodyStatusRecord_Type)0, 0, {RestStatusRecord_init_default}, false, 0}
#define SleepStatusRecord_init_default           {CommonRecord_init_default, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0}
#define SleepLiteStatusRecord_init_default       {CommonRecord_init_default, 0, 0, 0}
#define RestStatusRecord_init_default            {CommonRecord_init_default, 0}
#define LiteActivityStatusRecord_init_default    {CommonRecord_init_default, 0}
#define StepStatusRecord_init_default            {CommonRecord_init_default, 0, 0}
#define BriskWalkStatusRecord_init_default       {CommonRecord_init_default, 0}
#define StairStatusRecord_init_default           {CommonRecord_init_default, 0}
#define RunStatusRecord_init_default             {CommonRecord_init_default, 0, {RunStatusRecord_Point_init_default, RunStatusRecord_Point_init_default, RunStatusRecord_Point_init_default, RunStatusRecord_Point_init_default, RunStatusRecord_Point_init_default}}
#define RunStatusRecord_Point_init_default       {0, 0, 0, 0, false, 0, false, 0, false, 0, false, 0}
#define OutdoorBikeStatusRecord_init_default     {CommonRecord_init_default, 0, {OutdoorBikeStatusRecord_Point_init_default, OutdoorBikeStatusRecord_Point_init_default, OutdoorBikeStatusRecord_Point_init_default, OutdoorBikeStatusRecord_Point_init_default, OutdoorBikeStatusRecord_Point_init_default}}
#define OutdoorBikeStatusRecord_Point_init_default {0, 0, 0, 0, false, 0, false, 0, false, 0, false, 0}
#define OutdoorWalkStatusRecord_init_default     {CommonRecord_init_default, 0, {OutdoorWalkStatusRecord_Point_init_default, OutdoorWalkStatusRecord_Point_init_default, OutdoorWalkStatusRecord_Point_init_default, OutdoorWalkStatusRecord_Point_init_default, OutdoorWalkStatusRecord_Point_init_default}}
#define OutdoorWalkStatusRecord_Point_init_default {0, 0, 0, 0, false, 0, false, 0, false, 0, false, 0}
#define IndoorRunStatusRecord_init_default       {CommonRecord_init_default, 0, {IndoorRunStatusRecord_Point_init_default, IndoorRunStatusRecord_Point_init_default, IndoorRunStatusRecord_Point_init_default, IndoorRunStatusRecord_Point_init_default, IndoorRunStatusRecord_Point_init_default}}
#define IndoorRunStatusRecord_Point_init_default {0, 0, 0, 0, false, 0, 0}
#define IndoorBikeStatusRecord_init_default      {CommonRecord_init_default, 0, {IndoorBikeStatusRecord_Point_init_default, IndoorBikeStatusRecord_Point_init_default, IndoorBikeStatusRecord_Point_init_default, IndoorBikeStatusRecord_Point_init_default, IndoorBikeStatusRecord_Point_init_default}}
#define IndoorBikeStatusRecord_Point_init_default {0, 0, 0, 0}
#define IndoorSwimmingStatusRecord_init_default  {CommonRecord_init_default, 0, {IndoorSwimmingStatusRecord_Point_init_default, IndoorSwimmingStatusRecord_Point_init_default, IndoorSwimmingStatusRecord_Point_init_default, IndoorSwimmingStatusRecord_Point_init_default, IndoorSwimmingStatusRecord_Point_init_default}}
#define IndoorSwimmingStatusRecord_Point_init_default {0, 0, 0, 0, 0, 0, 0, false, 0}
#define FreeTrainingStatusRecord_init_default    {CommonRecord_init_default, 0, {FreeTrainingStatusRecord_Point_init_default, FreeTrainingStatusRecord_Point_init_default, FreeTrainingStatusRecord_Point_init_default, FreeTrainingStatusRecord_Point_init_default, FreeTrainingStatusRecord_Point_init_default}}
#define FreeTrainingStatusRecord_Point_init_default {0, 0, 0, 0}
#define RideStatusRecord_init_default            {CommonRecord_init_default}
#define SwimStatusRecord_init_default            {CommonRecord_init_default}
#define HeartRateRecord_init_zero                {0, 0, (HeartRateRecord_MeasureType)0, 0}
#define CommonRecord_init_zero                   {0, 0, 0, {HeartRateRecord_init_zero, HeartRateRecord_init_zero, HeartRateRecord_init_zero, HeartRateRecord_init_zero, HeartRateRecord_init_zero}, false, 0, false, 0, false, 0, 0, 0, 0, false, 0, false, 0}
#define BodyStatusRecord_init_zero               {(BodyStatusRecord_Type)0, 0, {RestStatusRecord_init_zero}, false, 0}
#define SleepStatusRecord_init_zero              {CommonRecord_init_zero, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0}
#define SleepLiteStatusRecord_init_zero          {CommonRecord_init_zero, 0, 0, 0}
#define RestStatusRecord_init_zero               {CommonRecord_init_zero, 0}
#define LiteActivityStatusRecord_init_zero       {CommonRecord_init_zero, 0}
#define StepStatusRecord_init_zero               {CommonRecord_init_zero, 0, 0}
#define BriskWalkStatusRecord_init_zero          {CommonRecord_init_zero, 0}
#define StairStatusRecord_init_zero              {CommonRecord_init_zero, 0}
#define RunStatusRecord_init_zero                {CommonRecord_init_zero, 0, {RunStatusRecord_Point_init_zero, RunStatusRecord_Point_init_zero, RunStatusRecord_Point_init_zero, RunStatusRecord_Point_init_zero, RunStatusRecord_Point_init_zero}}
#define RunStatusRecord_Point_init_zero          {0, 0, 0, 0, false, 0, false, 0, false, 0, false, 0}
#define OutdoorBikeStatusRecord_init_zero        {CommonRecord_init_zero, 0, {OutdoorBikeStatusRecord_Point_init_zero, OutdoorBikeStatusRecord_Point_init_zero, OutdoorBikeStatusRecord_Point_init_zero, OutdoorBikeStatusRecord_Point_init_zero, OutdoorBikeStatusRecord_Point_init_zero}}
#define OutdoorBikeStatusRecord_Point_init_zero  {0, 0, 0, 0, false, 0, false, 0, false, 0, false, 0}
#define OutdoorWalkStatusRecord_init_zero        {CommonRecord_init_zero, 0, {OutdoorWalkStatusRecord_Point_init_zero, OutdoorWalkStatusRecord_Point_init_zero, OutdoorWalkStatusRecord_Point_init_zero, OutdoorWalkStatusRecord_Point_init_zero, OutdoorWalkStatusRecord_Point_init_zero}}
#define OutdoorWalkStatusRecord_Point_init_zero  {0, 0, 0, 0, false, 0, false, 0, false, 0, false, 0}
#define IndoorRunStatusRecord_init_zero          {CommonRecord_init_zero, 0, {IndoorRunStatusRecord_Point_init_zero, IndoorRunStatusRecord_Point_init_zero, IndoorRunStatusRecord_Point_init_zero, IndoorRunStatusRecord_Point_init_zero, IndoorRunStatusRecord_Point_init_zero}}
#define IndoorRunStatusRecord_Point_init_zero    {0, 0, 0, 0, false, 0, 0}
#define IndoorBikeStatusRecord_init_zero         {CommonRecord_init_zero, 0, {IndoorBikeStatusRecord_Point_init_zero, IndoorBikeStatusRecord_Point_init_zero, IndoorBikeStatusRecord_Point_init_zero, IndoorBikeStatusRecord_Point_init_zero, IndoorBikeStatusRecord_Point_init_zero}}
#define IndoorBikeStatusRecord_Point_init_zero   {0, 0, 0, 0}
#define IndoorSwimmingStatusRecord_init_zero     {CommonRecord_init_zero, 0, {IndoorSwimmingStatusRecord_Point_init_zero, IndoorSwimmingStatusRecord_Point_init_zero, IndoorSwimmingStatusRecord_Point_init_zero, IndoorSwimmingStatusRecord_Point_init_zero, IndoorSwimmingStatusRecord_Point_init_zero}}
#define IndoorSwimmingStatusRecord_Point_init_zero {0, 0, 0, 0, 0, 0, 0, false, 0}
#define FreeTrainingStatusRecord_init_zero       {CommonRecord_init_zero, 0, {FreeTrainingStatusRecord_Point_init_zero, FreeTrainingStatusRecord_Point_init_zero, FreeTrainingStatusRecord_Point_init_zero, FreeTrainingStatusRecord_Point_init_zero, FreeTrainingStatusRecord_Point_init_zero}}
#define FreeTrainingStatusRecord_Point_init_zero {0, 0, 0, 0}
#define RideStatusRecord_init_zero               {CommonRecord_init_zero}
#define SwimStatusRecord_init_zero               {CommonRecord_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define FreeTrainingStatusRecord_Point_time_tag  1
#define FreeTrainingStatusRecord_Point_step_tag  2
#define FreeTrainingStatusRecord_Point_heart_rate_tag 3
#define FreeTrainingStatusRecord_Point_calorie_tag 4
#define HeartRateRecord_rate_tag                 1
#define HeartRateRecord_time_tag                 2
#define HeartRateRecord_measure_type_tag         3
#define HeartRateRecord_is_resting_tag           4
#define IndoorBikeStatusRecord_Point_time_tag    1
#define IndoorBikeStatusRecord_Point_step_tag    2
#define IndoorBikeStatusRecord_Point_heart_rate_tag 3
#define IndoorBikeStatusRecord_Point_calorie_tag 4
#define IndoorRunStatusRecord_Point_time_tag     1
#define IndoorRunStatusRecord_Point_step_tag     2
#define IndoorRunStatusRecord_Point_heart_rate_tag 3
#define IndoorRunStatusRecord_Point_calorie_tag  4
#define IndoorRunStatusRecord_Point_distance_tag 5
#define IndoorRunStatusRecord_Point_step_freq_tag 6
#define IndoorSwimmingStatusRecord_Point_time_tag 1
#define IndoorSwimmingStatusRecord_Point_step_tag 2
#define IndoorSwimmingStatusRecord_Point_heart_rate_tag 3
#define IndoorSwimmingStatusRecord_Point_calorie_tag 4
#define IndoorSwimmingStatusRecord_Point_distance_tag 5
#define IndoorSwimmingStatusRecord_Point_strokes_cnt_tag 6
#define IndoorSwimmingStatusRecord_Point_swolf_tag 7
#define IndoorSwimmingStatusRecord_Point_SwimmingPosture_tag 8
#define OutdoorBikeStatusRecord_Point_time_tag   1
#define OutdoorBikeStatusRecord_Point_step_tag   2
#define OutdoorBikeStatusRecord_Point_heart_rate_tag 3
#define OutdoorBikeStatusRecord_Point_calorie_tag 4
#define OutdoorBikeStatusRecord_Point_longitude_tag 5
#define OutdoorBikeStatusRecord_Point_latitude_tag 6
#define OutdoorBikeStatusRecord_Point_distance_tag 7
#define OutdoorBikeStatusRecord_Point_gps_status_tag 8
#define OutdoorWalkStatusRecord_Point_time_tag   1
#define OutdoorWalkStatusRecord_Point_step_tag   2
#define OutdoorWalkStatusRecord_Point_heart_rate_tag 3
#define OutdoorWalkStatusRecord_Point_calorie_tag 4
#define OutdoorWalkStatusRecord_Point_longitude_tag 5
#define OutdoorWalkStatusRecord_Point_latitude_tag 6
#define OutdoorWalkStatusRecord_Point_distance_tag 7
#define OutdoorWalkStatusRecord_Point_gps_status_tag 8
#define RunStatusRecord_Point_time_tag           1
#define RunStatusRecord_Point_step_tag           2
#define RunStatusRecord_Point_heart_rate_tag     3
#define RunStatusRecord_Point_calorie_tag        4
#define RunStatusRecord_Point_longitude_tag      5
#define RunStatusRecord_Point_latitude_tag       6
#define RunStatusRecord_Point_distance_tag       7
#define RunStatusRecord_Point_gps_status_tag     8
#define CommonRecord_start_time_tag              1
#define CommonRecord_end_time_tag                2
#define CommonRecord_heart_rates_tag             3
#define CommonRecord_calorie_tag                 4
#define CommonRecord_distance_tag                5
#define CommonRecord_long_sit_tag                6
#define CommonRecord_session_id_tag              7
#define CommonRecord_total_tag                   8
#define CommonRecord_sn_tag                      9
#define CommonRecord_deviation_tag               10
#define CommonRecord_daylight_tag                11
#define BriskWalkStatusRecord_common_tag         1
#define BriskWalkStatusRecord_step_tag           20
#define FreeTrainingStatusRecord_common_tag      1
#define FreeTrainingStatusRecord_point_tag       20
#define IndoorBikeStatusRecord_common_tag        1
#define IndoorBikeStatusRecord_point_tag         20
#define IndoorRunStatusRecord_common_tag         1
#define IndoorRunStatusRecord_point_tag          20
#define IndoorSwimmingStatusRecord_common_tag    1
#define IndoorSwimmingStatusRecord_point_tag     20
#define LiteActivityStatusRecord_common_tag      1
#define LiteActivityStatusRecord_step_tag        20
#define OutdoorBikeStatusRecord_common_tag       1
#define OutdoorBikeStatusRecord_point_tag        20
#define OutdoorWalkStatusRecord_common_tag       1
#define OutdoorWalkStatusRecord_point_tag        20
#define RestStatusRecord_common_tag              1
#define RestStatusRecord_step_tag                20
#define RideStatusRecord_common_tag              1
#define RunStatusRecord_common_tag               1
#define RunStatusRecord_point_tag                20
#define SleepLiteStatusRecord_common_tag         1
#define SleepLiteStatusRecord_version_tag        2
#define SleepLiteStatusRecord_type_tag           3
#define SleepLiteStatusRecord_step_tag           21
#define SleepStatusRecord_common_tag             1
#define SleepStatusRecord_version_tag            2
#define SleepStatusRecord_rris_tag               20
#define SleepStatusRecord_step_tag               21
#define StairStatusRecord_common_tag             1
#define StairStatusRecord_step_tag               20
#define StepStatusRecord_common_tag              1
#define StepStatusRecord_step_tag                20
#define StepStatusRecord_freq_tag                21
#define SwimStatusRecord_common_tag              1
#define BodyStatusRecord_rest_tag                2
#define BodyStatusRecord_lite_activity_tag       3
#define BodyStatusRecord_step_tag                4
#define BodyStatusRecord_brisk_walk_tag          5
#define BodyStatusRecord_stair_tag               6
#define BodyStatusRecord_run_tag                 7
#define BodyStatusRecord_ride_tag                8
#define BodyStatusRecord_swim_tag                9
#define BodyStatusRecord_sleep_lite_tag          10
#define BodyStatusRecord_outdoor_walk_tag        11
#define BodyStatusRecord_indoor_run_tag          12
#define BodyStatusRecord_indoor_ride_tag         13
#define BodyStatusRecord_free_tag                14
#define BodyStatusRecord_outdoor_ride_tag        15
#define BodyStatusRecord_indoor_swim_tag         16
#define BodyStatusRecord_type_tag                1
#define BodyStatusRecord_today_step_tag          17

/* Struct field encoding specification for nanopb */
extern const pb_field_t HeartRateRecord_fields[5];
extern const pb_field_t CommonRecord_fields[12];
extern const pb_field_t BodyStatusRecord_fields[18];
extern const pb_field_t SleepStatusRecord_fields[5];
extern const pb_field_t SleepLiteStatusRecord_fields[5];
extern const pb_field_t RestStatusRecord_fields[3];
extern const pb_field_t LiteActivityStatusRecord_fields[3];
extern const pb_field_t StepStatusRecord_fields[4];
extern const pb_field_t BriskWalkStatusRecord_fields[3];
extern const pb_field_t StairStatusRecord_fields[3];
extern const pb_field_t RunStatusRecord_fields[3];
extern const pb_field_t RunStatusRecord_Point_fields[9];
extern const pb_field_t OutdoorBikeStatusRecord_fields[3];
extern const pb_field_t OutdoorBikeStatusRecord_Point_fields[9];
extern const pb_field_t OutdoorWalkStatusRecord_fields[3];
extern const pb_field_t OutdoorWalkStatusRecord_Point_fields[9];
extern const pb_field_t IndoorRunStatusRecord_fields[3];
extern const pb_field_t IndoorRunStatusRecord_Point_fields[7];
extern const pb_field_t IndoorBikeStatusRecord_fields[3];
extern const pb_field_t IndoorBikeStatusRecord_Point_fields[5];
extern const pb_field_t IndoorSwimmingStatusRecord_fields[3];
extern const pb_field_t IndoorSwimmingStatusRecord_Point_fields[9];
extern const pb_field_t FreeTrainingStatusRecord_fields[3];
extern const pb_field_t FreeTrainingStatusRecord_Point_fields[5];
extern const pb_field_t RideStatusRecord_fields[2];
extern const pb_field_t SwimStatusRecord_fields[2];

/* Maximum encoded size of messages (where known) */
#define HeartRateRecord_size                     26
#define CommonRecord_size                        228 + 22
#define BodyStatusRecord_size                    674
#define SleepStatusRecord_size                   879
#define SleepLiteStatusRecord_size               260
#define RestStatusRecord_size                    243
#define LiteActivityStatusRecord_size            243
#define StepStatusRecord_size                    255
#define BriskWalkStatusRecord_size               243
#define StairStatusRecord_size                   243
#define RunStatusRecord_size                     591
#define RunStatusRecord_Point_size               69
#define OutdoorBikeStatusRecord_size             591
#define OutdoorBikeStatusRecord_Point_size       69
#define OutdoorWalkStatusRecord_size             591
#define OutdoorWalkStatusRecord_Point_size       69
#define IndoorRunStatusRecord_size               546
#define IndoorRunStatusRecord_Point_size         60
#define IndoorBikeStatusRecord_size              466
#define IndoorBikeStatusRecord_Point_size        44
#define IndoorSwimmingStatusRecord_size          656
#define IndoorSwimmingStatusRecord_Point_size    82
#define FreeTrainingStatusRecord_size            466
#define FreeTrainingStatusRecord_Point_size      44
#define RideStatusRecord_size                    231
#define SwimStatusRecord_size                    231

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define BODYSTATUS_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
