/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Fri Aug 03 10:40:50 2018. */

#include "DataUpload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t DataRecord_fields[3] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, DataRecord, data_type, data_type, 0),
    PB_FIELD(  2, BYTES   , REQUIRED, CALLBACK, OTHER, DataRecord, val, data_type, 0),
    PB_LAST_FIELD
};

const pb_field_t DataSet_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, DataSet, did, did, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, DataSet, records, did, &DataRecord_fields),
    PB_LAST_FIELD
};

const pb_field_t UploadDataStartParam_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, UploadDataStartParam, dataset_num, dataset_num, 0),
    PB_LAST_FIELD
};



/* @@protoc_insertion_point(eof) */
