/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Fri Aug 17 16:42:29 2018. */

#include "DefaultCard.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t DefaultCardInfo_fields[4] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, DefaultCardInfo, mode, mode, 0),
    PB_FIELD(  2, BYTES   , OPTIONAL, STATIC  , OTHER, DefaultCardInfo, id, mode, 0),
    PB_FIELD(  3, UENUM   , OPTIONAL, STATIC  , OTHER, DefaultCardInfo, type, id, 0),
    PB_LAST_FIELD
};




/* @@protoc_insertion_point(eof) */
