/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Fri Aug 17 16:42:29 2018. */

#ifndef PB_DEFAULTCARD_PB_H_INCLUDED
#define PB_DEFAULTCARD_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _DefaultCardInfo_Mode {
    DefaultCardInfo_Mode_LAST_USE = 1,
    DefaultCardInfo_Mode_SPECIFIC = 2
} DefaultCardInfo_Mode;
#define _DefaultCardInfo_Mode_MIN DefaultCardInfo_Mode_LAST_USE
#define _DefaultCardInfo_Mode_MAX DefaultCardInfo_Mode_SPECIFIC
#define _DefaultCardInfo_Mode_ARRAYSIZE ((DefaultCardInfo_Mode)(DefaultCardInfo_Mode_SPECIFIC+1))

typedef enum _DefaultCardInfo_CardType {
    DefaultCardInfo_CardType_TRANSIT_CARD = 1,
    DefaultCardInfo_CardType_GATE_CARD = 2
} DefaultCardInfo_CardType;
#define _DefaultCardInfo_CardType_MIN DefaultCardInfo_CardType_TRANSIT_CARD
#define _DefaultCardInfo_CardType_MAX DefaultCardInfo_CardType_GATE_CARD
#define _DefaultCardInfo_CardType_ARRAYSIZE ((DefaultCardInfo_CardType)(DefaultCardInfo_CardType_GATE_CARD+1))

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(18) DefaultCardInfo_id_t;
typedef struct _DefaultCardInfo {
    DefaultCardInfo_Mode mode;
    bool has_id;
    DefaultCardInfo_id_t id;
    bool has_type;
    DefaultCardInfo_CardType type;
/* @@protoc_insertion_point(struct:DefaultCardInfo) */
} DefaultCardInfo;

/* Default values for struct fields */

/* Initializer values for message structs */
#define DefaultCardInfo_init_default             {(DefaultCardInfo_Mode)0, false, {0, {0}}, false, (DefaultCardInfo_CardType)0}
#define DefaultCardInfo_init_zero                {(DefaultCardInfo_Mode)0, false, {0, {0}}, false, (DefaultCardInfo_CardType)0}

/* Field tags (for use in manual encoding/decoding) */
#define DefaultCardInfo_mode_tag                 1
#define DefaultCardInfo_id_tag                   2
#define DefaultCardInfo_type_tag                 3

/* Struct field encoding specification for nanopb */
extern const pb_field_t DefaultCardInfo_fields[4];

/* Maximum encoded size of messages (where known) */
#define DefaultCardInfo_size                     24

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define DEFAULTCARD_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
