/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Mon Apr 23 00:24:31 2018. */

#ifndef PB_DEVAPP_PB_H_INCLUDED
#define PB_DEVAPP_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _DevAppInfo {
    int32_t id;
/* @@protoc_insertion_point(struct:DevAppInfo) */
} DevAppInfo;

typedef struct _DevAppList {
    pb_size_t dev_app_infos_count;
    DevAppInfo dev_app_infos[10];
/* @@protoc_insertion_point(struct:DevAppList) */
} DevAppList;

/* Default values for struct fields */

/* Initializer values for message structs */
#define DevAppInfo_init_default                  {0}
#define DevAppList_init_default                  {0, {DevAppInfo_init_default, DevAppInfo_init_default, DevAppInfo_init_default, DevAppInfo_init_default, DevAppInfo_init_default, DevAppInfo_init_default, DevAppInfo_init_default, DevAppInfo_init_default, DevAppInfo_init_default, DevAppInfo_init_default}}
#define DevAppInfo_init_zero                     {0}
#define DevAppList_init_zero                     {0, {DevAppInfo_init_zero, DevAppInfo_init_zero, DevAppInfo_init_zero, DevAppInfo_init_zero, DevAppInfo_init_zero, DevAppInfo_init_zero, DevAppInfo_init_zero, DevAppInfo_init_zero, DevAppInfo_init_zero, DevAppInfo_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define DevAppInfo_id_tag                        1
#define DevAppList_dev_app_infos_tag             1

/* Struct field encoding specification for nanopb */
extern const pb_field_t DevAppInfo_fields[2];
extern const pb_field_t DevAppList_fields[2];

/* Maximum encoded size of messages (where known) */
#define DevAppInfo_size                          11
#define DevAppList_size                          130

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define DEVAPP_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
