/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Sat Sep 01 18:57:24 2018. */

#include "DevStatistics.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t StatisticsTimestampValuePair_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, StatisticsTimestampValuePair, timestamp, timestamp, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, StatisticsTimestampValuePair, value, timestamp, 0),
    PB_LAST_FIELD
};

const pb_field_t DevStatisticsResultRecord_fields[5] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, DevStatisticsResultRecord, cmd, cmd, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, DevStatisticsResultRecord, desc_type, cmd, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, DevStatisticsResultRecord, counter, desc_type, 0),
    PB_FIELD(  5, MESSAGE , REPEATED, STATIC  , OTHER, DevStatisticsResultRecord, time_value, counter, &StatisticsTimestampValuePair_fields),
    PB_LAST_FIELD
};

const pb_field_t DevStatisticsResult_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, DevStatisticsResult, start_time, start_time, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, DevStatisticsResult, end_time, start_time, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, STATIC  , OTHER, DevStatisticsResult, records, end_time, &DevStatisticsResultRecord_fields),
    PB_LAST_FIELD
};




/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(DevStatisticsResultRecord, time_value[0]) < 65536 && pb_membersize(DevStatisticsResult, records[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_StatisticsTimestampValuePair_DevStatisticsResultRecord_DevStatisticsResult)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(DevStatisticsResultRecord, time_value[0]) < 256 && pb_membersize(DevStatisticsResult, records[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_StatisticsTimestampValuePair_DevStatisticsResultRecord_DevStatisticsResult)
#endif


/* @@protoc_insertion_point(eof) */
