/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Mon Jun 25 19:01:25 2018. */

#include "Firmware.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t FwUpdateInfo_fields[5] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, FwUpdateInfo, version, version, 0),
    PB_FIELD(  2, BOOL    , REQUIRED, STATIC  , OTHER, FwUpdateInfo, force, version, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, STATIC  , OTHER, FwUpdateInfo, items, force, &FwUpdateItem_fields),
    PB_FIELD(  4, INT32   , OPTIONAL, STATIC  , OTHER, FwUpdateInfo, ota_conn_interval, items, 0),
    PB_LAST_FIELD
};

const pb_field_t FwUpdateItem_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, FwUpdateItem, fw_id, fw_id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, FwUpdateItem, length, fw_id, 0),
    PB_LAST_FIELD
};

const pb_field_t FwUpdateStartResult_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, FwUpdateStartResult, transfered_length, transfered_length, 0),
    PB_LAST_FIELD
};

const pb_field_t FwUpdateTokenResult_fields[2] = {
    PB_FIELD(  1, BYTES   , REQUIRED, STATIC  , FIRST, FwUpdateTokenResult, device_token, device_token, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(FwUpdateInfo, items[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_FwUpdateInfo_FwUpdateItem_FwUpdateStartResult_FwUpdateTokenResult)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(FwUpdateInfo, items[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_FwUpdateInfo_FwUpdateItem_FwUpdateStartResult_FwUpdateTokenResult)
#endif


/* @@protoc_insertion_point(eof) */
