/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Mon Jun 25 19:01:25 2018. */

#ifndef PB_FIRMWARE_PB_H_INCLUDED
#define PB_FIRMWARE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _FwUpdateItem {
    int32_t fw_id;
    int32_t length;
/* @@protoc_insertion_point(struct:FwUpdateItem) */
} FwUpdateItem;

typedef struct _FwUpdateStartResult {
    int32_t transfered_length;
/* @@protoc_insertion_point(struct:FwUpdateStartResult) */
} FwUpdateStartResult;

typedef PB_BYTES_ARRAY_T(64) FwUpdateTokenResult_device_token_t;
typedef struct _FwUpdateTokenResult {
    FwUpdateTokenResult_device_token_t device_token;
/* @@protoc_insertion_point(struct:FwUpdateTokenResult) */
} FwUpdateTokenResult;

typedef struct _FwUpdateInfo {
    char version[50];
    bool force;
    pb_size_t items_count;
    FwUpdateItem items[10];
    bool has_ota_conn_interval;
    int32_t ota_conn_interval;
/* @@protoc_insertion_point(struct:FwUpdateInfo) */
} FwUpdateInfo;

/* Default values for struct fields */

/* Initializer values for message structs */
#define FwUpdateInfo_init_default                {"", 0, 0, {FwUpdateItem_init_default, FwUpdateItem_init_default, FwUpdateItem_init_default, FwUpdateItem_init_default, FwUpdateItem_init_default, FwUpdateItem_init_default, FwUpdateItem_init_default, FwUpdateItem_init_default, FwUpdateItem_init_default, FwUpdateItem_init_default}, false, 0}
#define FwUpdateItem_init_default                {0, 0}
#define FwUpdateStartResult_init_default         {0}
#define FwUpdateTokenResult_init_default         {{0, {0}}}
#define FwUpdateInfo_init_zero                   {"", 0, 0, {FwUpdateItem_init_zero, FwUpdateItem_init_zero, FwUpdateItem_init_zero, FwUpdateItem_init_zero, FwUpdateItem_init_zero, FwUpdateItem_init_zero, FwUpdateItem_init_zero, FwUpdateItem_init_zero, FwUpdateItem_init_zero, FwUpdateItem_init_zero}, false, 0}
#define FwUpdateItem_init_zero                   {0, 0}
#define FwUpdateStartResult_init_zero            {0}
#define FwUpdateTokenResult_init_zero            {{0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define FwUpdateItem_fw_id_tag                   1
#define FwUpdateItem_length_tag                  2
#define FwUpdateStartResult_transfered_length_tag 1
#define FwUpdateTokenResult_device_token_tag     1
#define FwUpdateInfo_version_tag                 1
#define FwUpdateInfo_force_tag                   2
#define FwUpdateInfo_items_tag                   3
#define FwUpdateInfo_ota_conn_interval_tag       4

/* Struct field encoding specification for nanopb */
extern const pb_field_t FwUpdateInfo_fields[5];
extern const pb_field_t FwUpdateItem_fields[3];
extern const pb_field_t FwUpdateStartResult_fields[2];
extern const pb_field_t FwUpdateTokenResult_fields[2];

/* Maximum encoded size of messages (where known) */
#define FwUpdateInfo_size                        305
#define FwUpdateItem_size                        22
#define FwUpdateStartResult_size                 11
#define FwUpdateTokenResult_size                 66

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define FIRMWARE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
