/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Sat Nov 11 18:28:12 2017. */

#ifndef PB_FIT_HEALTH_PB_H_INCLUDED
#define PB_FIT_HEALTH_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _FH_TYPE {
    FH_TYPE_PEDOMETER = 0,
    FH_TYPE_RUNNING = 1,
    FH_TYPE_HEART_RATE = 2,
    FH_TYPE_SLEEP = 3,
    FH_TYPE_SWIMING = 4,
    FH_TYPE_RIDING = 5
} FH_TYPE;
#define _FH_TYPE_MIN FH_TYPE_PEDOMETER
#define _FH_TYPE_MAX FH_TYPE_RIDING
#define _FH_TYPE_ARRAYSIZE ((FH_TYPE)(FH_TYPE_RIDING+1))

typedef enum _FH_SUB_TYPE {
    FH_SUB_TYPE_INSTANT = 0,
    FH_SUB_TYPE_DETAIL = 1,
    FH_SUB_TYPE_HISTORY = 2,
    FH_SUB_TYPE_RAW = 3,
    FH_SUB_TYPE_PARAMETERS = 4
} FH_SUB_TYPE;
#define _FH_SUB_TYPE_MIN FH_SUB_TYPE_INSTANT
#define _FH_SUB_TYPE_MAX FH_SUB_TYPE_PARAMETERS
#define _FH_SUB_TYPE_ARRAYSIZE ((FH_SUB_TYPE)(FH_SUB_TYPE_PARAMETERS+1))

/* Struct definitions */
typedef struct _FitHealthMsg {
    FH_TYPE type;
    FH_SUB_TYPE subtype;
    pb_callback_t val;
/* @@protoc_insertion_point(struct:FitHealthMsg) */
} FitHealthMsg;

typedef struct _FitHealthMsg_PedoHistory {
    FH_TYPE type;
    FH_SUB_TYPE subtype;
    pb_callback_t details;
/* @@protoc_insertion_point(struct:FitHealthMsg_PedoHistory) */
} FitHealthMsg_PedoHistory;

typedef struct _FitHealthMsg_PedoInst {
    FH_TYPE type;
    FH_SUB_TYPE subtype;
    int32_t steps;
/* @@protoc_insertion_point(struct:FitHealthMsg_PedoInst) */
} FitHealthMsg_PedoInst;

typedef struct _FitHealthMsg_PedoRaw {
    FH_TYPE type;
    FH_SUB_TYPE subtype;
    pb_callback_t detail;
/* @@protoc_insertion_point(struct:FitHealthMsg_PedoRaw) */
} FitHealthMsg_PedoRaw;

typedef struct _PedoDetail {
    int32_t steps;
    int32_t starttime;
    int32_t endtime;
/* @@protoc_insertion_point(struct:PedoDetail) */
} PedoDetail;

typedef struct _PedoRaw {
    int32_t x;
    int32_t y;
    int32_t z;
    int32_t time;
/* @@protoc_insertion_point(struct:PedoRaw) */
} PedoRaw;

typedef struct _FitHealthMsg_PedoDetail {
    FH_TYPE type;
    FH_SUB_TYPE subtype;
    PedoDetail detail;
/* @@protoc_insertion_point(struct:FitHealthMsg_PedoDetail) */
} FitHealthMsg_PedoDetail;

/* Default values for struct fields */

/* Initializer values for message structs */
#define PedoDetail_init_default                  {0, 0, 0}
#define PedoRaw_init_default                     {0, 0, 0, 0}
#define FitHealthMsg_PedoInst_init_default       {(FH_TYPE)0, (FH_SUB_TYPE)0, 0}
#define FitHealthMsg_PedoDetail_init_default     {(FH_TYPE)0, (FH_SUB_TYPE)0, PedoDetail_init_default}
#define FitHealthMsg_PedoHistory_init_default    {(FH_TYPE)0, (FH_SUB_TYPE)0, {{NULL}, NULL}}
#define FitHealthMsg_PedoRaw_init_default        {(FH_TYPE)0, (FH_SUB_TYPE)0, {{NULL}, NULL}}
#define FitHealthMsg_init_default                {(FH_TYPE)0, (FH_SUB_TYPE)0, {{NULL}, NULL}}
#define PedoDetail_init_zero                     {0, 0, 0}
#define PedoRaw_init_zero                        {0, 0, 0, 0}
#define FitHealthMsg_PedoInst_init_zero          {(FH_TYPE)0, (FH_SUB_TYPE)0, 0}
#define FitHealthMsg_PedoDetail_init_zero        {(FH_TYPE)0, (FH_SUB_TYPE)0, PedoDetail_init_zero}
#define FitHealthMsg_PedoHistory_init_zero       {(FH_TYPE)0, (FH_SUB_TYPE)0, {{NULL}, NULL}}
#define FitHealthMsg_PedoRaw_init_zero           {(FH_TYPE)0, (FH_SUB_TYPE)0, {{NULL}, NULL}}
#define FitHealthMsg_init_zero                   {(FH_TYPE)0, (FH_SUB_TYPE)0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define FitHealthMsg_type_tag                    1
#define FitHealthMsg_subtype_tag                 2
#define FitHealthMsg_val_tag                     3
#define FitHealthMsg_PedoHistory_type_tag        1
#define FitHealthMsg_PedoHistory_subtype_tag     2
#define FitHealthMsg_PedoHistory_details_tag     3
#define FitHealthMsg_PedoInst_type_tag           1
#define FitHealthMsg_PedoInst_subtype_tag        2
#define FitHealthMsg_PedoInst_steps_tag          3
#define FitHealthMsg_PedoRaw_type_tag            1
#define FitHealthMsg_PedoRaw_subtype_tag         2
#define FitHealthMsg_PedoRaw_detail_tag          3
#define PedoDetail_steps_tag                     1
#define PedoDetail_starttime_tag                 2
#define PedoDetail_endtime_tag                   3
#define PedoRaw_x_tag                            1
#define PedoRaw_y_tag                            2
#define PedoRaw_z_tag                            3
#define PedoRaw_time_tag                         4
#define FitHealthMsg_PedoDetail_type_tag         1
#define FitHealthMsg_PedoDetail_subtype_tag      2
#define FitHealthMsg_PedoDetail_detail_tag       3

/* Struct field encoding specification for nanopb */
extern const pb_field_t PedoDetail_fields[4];
extern const pb_field_t PedoRaw_fields[5];
extern const pb_field_t FitHealthMsg_PedoInst_fields[4];
extern const pb_field_t FitHealthMsg_PedoDetail_fields[4];
extern const pb_field_t FitHealthMsg_PedoHistory_fields[4];
extern const pb_field_t FitHealthMsg_PedoRaw_fields[4];
extern const pb_field_t FitHealthMsg_fields[4];

/* Maximum encoded size of messages (where known) */
#define PedoDetail_size                          33
#define PedoRaw_size                             44
#define FitHealthMsg_PedoInst_size               15
#define FitHealthMsg_PedoDetail_size             39
/* FitHealthMsg_PedoHistory_size depends on runtime parameters */
/* FitHealthMsg_PedoRaw_size depends on runtime parameters */
/* FitHealthMsg_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define FIT_HEALTH_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
