/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Sat Nov 11 18:28:12 2017. */

#include "fit_health.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t PedoDetail_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, PedoDetail, steps, steps, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, PedoDetail, starttime, steps, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, PedoDetail, endtime, starttime, 0),
    PB_LAST_FIELD
};

const pb_field_t PedoRaw_fields[5] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, PedoRaw, x, x, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, PedoRaw, y, x, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, PedoRaw, z, y, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, PedoRaw, time, z, 0),
    PB_LAST_FIELD
};

const pb_field_t FitHealthMsg_PedoInst_fields[4] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, FitHealthMsg_PedoInst, type, type, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, FitHealthMsg_PedoInst, subtype, type, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, FitHealthMsg_PedoInst, steps, subtype, 0),
    PB_LAST_FIELD
};

const pb_field_t FitHealthMsg_PedoDetail_fields[4] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, FitHealthMsg_PedoDetail, type, type, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, FitHealthMsg_PedoDetail, subtype, type, 0),
    PB_FIELD(  3, MESSAGE , REQUIRED, STATIC  , OTHER, FitHealthMsg_PedoDetail, detail, subtype, &PedoDetail_fields),
    PB_LAST_FIELD
};

const pb_field_t FitHealthMsg_PedoHistory_fields[4] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, FitHealthMsg_PedoHistory, type, type, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, FitHealthMsg_PedoHistory, subtype, type, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, FitHealthMsg_PedoHistory, details, subtype, &PedoDetail_fields),
    PB_LAST_FIELD
};

const pb_field_t FitHealthMsg_PedoRaw_fields[4] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, FitHealthMsg_PedoRaw, type, type, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, FitHealthMsg_PedoRaw, subtype, type, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, FitHealthMsg_PedoRaw, detail, subtype, &PedoRaw_fields),
    PB_LAST_FIELD
};

const pb_field_t FitHealthMsg_fields[4] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, FitHealthMsg, type, type, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, FitHealthMsg, subtype, type, 0),
    PB_FIELD(  3, BYTES   , OPTIONAL, CALLBACK, OTHER, FitHealthMsg, val, subtype, 0),
    PB_LAST_FIELD
};




/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(FitHealthMsg_PedoDetail, detail) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_PedoDetail_PedoRaw_FitHealthMsg_PedoInst_FitHealthMsg_PedoDetail_FitHealthMsg_PedoHistory_FitHealthMsg_PedoRaw_FitHealthMsg)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(FitHealthMsg_PedoDetail, detail) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_PedoDetail_PedoRaw_FitHealthMsg_PedoInst_FitHealthMsg_PedoDetail_FitHealthMsg_PedoHistory_FitHealthMsg_PedoRaw_FitHealthMsg)
#endif


/* @@protoc_insertion_point(eof) */
