/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Tue Jul 24 16:01:55 2018. */

#include "Gate.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t GateCheckResult_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, GateCheckResult, code, code, 0),
    PB_FIELD(  2, BYTES   , OPTIONAL, STATIC  , OTHER, GateCheckResult, uid, code, 0),
    PB_LAST_FIELD
};

const pb_field_t GateCreateParam_fields[2] = {
    PB_FIELD(  1, BYTES   , REQUIRED, STATIC  , FIRST, GateCreateParam, aid, aid, 0),
    PB_LAST_FIELD
};

const pb_field_t GateCreateAck_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, GateCreateAck, code, code, 0),
    PB_LAST_FIELD
};

const pb_field_t GateCardInfo_fields[4] = {
    PB_FIELD(  1, BYTES   , REQUIRED, STATIC  , FIRST, GateCardInfo, aid, aid, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, GateCardInfo, name, aid, 0),
    PB_FIELD(  3, UENUM   , OPTIONAL, STATIC  , OTHER, GateCardInfo, type, name, 0),
    PB_LAST_FIELD
};

const pb_field_t GetGateInfoListResult_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, GetGateInfoListResult, card_infos, card_infos, &GateCardInfo_fields),
    PB_LAST_FIELD
};

const pb_field_t GateDeleteParam_fields[2] = {
    PB_FIELD(  1, BYTES   , REQUIRED, STATIC  , FIRST, GateDeleteParam, aid, aid, 0),
    PB_LAST_FIELD
};

const pb_field_t GateDeleteAck_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, GateDeleteAck, code, code, 0),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(GetGateInfoListResult, card_infos[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_GateCheckResult_GateCreateParam_GateCreateAck_GateCardInfo_GetGateInfoListResult_GateDeleteParam_GateDeleteAck)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(GetGateInfoListResult, card_infos[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_GateCheckResult_GateCreateParam_GateCreateAck_GateCardInfo_GetGateInfoListResult_GateDeleteParam_GateDeleteAck)
#endif


/* @@protoc_insertion_point(eof) */
