/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Mon Mar 12 16:32:35 2018. */

#include "Location.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t LocationRequest_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, LocationRequest, session_id, session_id, 0),
    PB_FIELD(  2, DOUBLE  , OPTIONAL, STATIC  , OTHER, LocationRequest, last_longitude, session_id, 0),
    PB_FIELD(  3, DOUBLE  , OPTIONAL, STATIC  , OTHER, LocationRequest, last_latitude, last_longitude, 0),
    PB_LAST_FIELD
};

const pb_field_t LocationResult_fields[5] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, LocationResult, session_id, session_id, 0),
    PB_FIELD(  2, DOUBLE  , REQUIRED, STATIC  , OTHER, LocationResult, longitude, session_id, 0),
    PB_FIELD(  3, DOUBLE  , REQUIRED, STATIC  , OTHER, LocationResult, latitude, longitude, 0),
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, LocationResult, last_distance, latitude, 0),
    PB_LAST_FIELD
};


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
