/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Sun Aug 05 17:55:09 2018. */

#include "MiScene.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t MiSceneLaunchInfo_fields[7] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, MiSceneLaunchInfo, launch_type, launch_type, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, MiSceneLaunchInfo, launch_name, launch_type, 0),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC  , OTHER, MiSceneLaunchInfo, model, launch_name, 0),
    PB_FIELD(  4, STRING  , REQUIRED, STATIC  , OTHER, MiSceneLaunchInfo, did, model, 0),
    PB_FIELD(  5, STRING  , REQUIRED, STATIC  , OTHER, MiSceneLaunchInfo, event_str, did, 0),
    PB_FIELD(  6, STRING  , REQUIRED, STATIC  , OTHER, MiSceneLaunchInfo, event_value, event_str, 0),
    PB_LAST_FIELD
};

const pb_field_t MiSceneActionInfo_fields[8] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, MiSceneActionInfo, action_type, action_type, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, MiSceneActionInfo, action_name, action_type, 0),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC  , OTHER, MiSceneActionInfo, action_str, action_name, 0),
    PB_FIELD(  4, STRING  , REQUIRED, STATIC  , OTHER, MiSceneActionInfo, action_value, action_str, 0),
    PB_FIELD(  5, STRING  , REQUIRED, STATIC  , OTHER, MiSceneActionInfo, model, action_value, 0),
    PB_FIELD(  6, STRING  , REQUIRED, STATIC  , OTHER, MiSceneActionInfo, did, model, 0),
    PB_FIELD(  7, STRING  , REQUIRED, STATIC  , OTHER, MiSceneActionInfo, device_name, did, 0),
    PB_LAST_FIELD
};

const pb_field_t MiSceneInfo_fields[7] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, MiSceneInfo, scene_id, scene_id, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, MiSceneInfo, mid, scene_id, 0),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC  , OTHER, MiSceneInfo, name, mid, 0),
    PB_FIELD(  4, MESSAGE , REPEATED, STATIC  , OTHER, MiSceneInfo, launchs, name, &MiSceneLaunchInfo_fields),
    PB_FIELD(  5, MESSAGE , REPEATED, STATIC  , OTHER, MiSceneInfo, actions, launchs, &MiSceneActionInfo_fields),
    PB_FIELD(  6, BOOL    , OPTIONAL, STATIC  , OTHER, MiSceneInfo, enable, actions, 0),
    PB_LAST_FIELD
};

const pb_field_t MiSceneList_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, MiSceneList, mi_scene_infos, mi_scene_infos, &MiSceneInfo_fields),
    PB_LAST_FIELD
};

const pb_field_t MiSceneDeleteParam_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, MiSceneDeleteParam, scene_id, scene_id, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, MiSceneDeleteParam, mid, scene_id, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(MiSceneInfo, launchs[0]) < 65536 && pb_membersize(MiSceneInfo, actions[0]) < 65536 && pb_membersize(MiSceneList, mi_scene_infos[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_MiSceneLaunchInfo_MiSceneActionInfo_MiSceneInfo_MiSceneList_MiSceneDeleteParam)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(MiSceneInfo, launchs[0]) < 256 && pb_membersize(MiSceneInfo, actions[0]) < 256 && pb_membersize(MiSceneList, mi_scene_infos[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_MiSceneLaunchInfo_MiSceneActionInfo_MiSceneInfo_MiSceneList_MiSceneDeleteParam)
#endif


/* @@protoc_insertion_point(eof) */
