/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Sun Aug 05 17:55:09 2018. */

#ifndef PB_MISCENE_PB_H_INCLUDED
#define PB_MISCENE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _MiSceneActionInfo {
    int32_t action_type;
    char action_name[40];
    char action_str[70];
    char action_value[50];
    char model[30];
    char did[30];
    char device_name[30];
/* @@protoc_insertion_point(struct:MiSceneActionInfo) */
} MiSceneActionInfo;

typedef struct _MiSceneDeleteParam {
    int32_t scene_id;
    char mid[20];
/* @@protoc_insertion_point(struct:MiSceneDeleteParam) */
} MiSceneDeleteParam;

typedef struct _MiSceneLaunchInfo {
    int32_t launch_type;
    char launch_name[40];
    char model[30];
    char did[30];
    char event_str[50];
    char event_value[20];
/* @@protoc_insertion_point(struct:MiSceneLaunchInfo) */
} MiSceneLaunchInfo;

typedef struct _MiSceneInfo {
    int32_t scene_id;
    char mid[20];
    char name[70];
    pb_size_t launchs_count;
    MiSceneLaunchInfo launchs[4];
    pb_size_t actions_count;
    MiSceneActionInfo actions[1];
    bool has_enable;
    bool enable;
/* @@protoc_insertion_point(struct:MiSceneInfo) */
} MiSceneInfo;

typedef struct _MiSceneList {
    pb_size_t mi_scene_infos_count;
    MiSceneInfo mi_scene_infos[5];
/* @@protoc_insertion_point(struct:MiSceneList) */
} MiSceneList;

/* Default values for struct fields */

/* Initializer values for message structs */
#define MiSceneLaunchInfo_init_default           {0, "", "", "", "", ""}
#define MiSceneActionInfo_init_default           {0, "", "", "", "", "", ""}
#define MiSceneInfo_init_default                 {0, "", "", 0, {MiSceneLaunchInfo_init_default, MiSceneLaunchInfo_init_default, MiSceneLaunchInfo_init_default, MiSceneLaunchInfo_init_default}, 0, {MiSceneActionInfo_init_default}, false, 0}
#define MiSceneList_init_default                 {0, {MiSceneInfo_init_default, MiSceneInfo_init_default, MiSceneInfo_init_default, MiSceneInfo_init_default, MiSceneInfo_init_default}}
#define MiSceneDeleteParam_init_default          {0, ""}
#define MiSceneLaunchInfo_init_zero              {0, "", "", "", "", ""}
#define MiSceneActionInfo_init_zero              {0, "", "", "", "", "", ""}
#define MiSceneInfo_init_zero                    {0, "", "", 0, {MiSceneLaunchInfo_init_zero, MiSceneLaunchInfo_init_zero, MiSceneLaunchInfo_init_zero, MiSceneLaunchInfo_init_zero}, 0, {MiSceneActionInfo_init_zero}, false, 0}
#define MiSceneList_init_zero                    {0, {MiSceneInfo_init_zero, MiSceneInfo_init_zero, MiSceneInfo_init_zero, MiSceneInfo_init_zero, MiSceneInfo_init_zero}}
#define MiSceneDeleteParam_init_zero             {0, ""}

/* Field tags (for use in manual encoding/decoding) */
#define MiSceneActionInfo_action_type_tag        1
#define MiSceneActionInfo_action_name_tag        2
#define MiSceneActionInfo_action_str_tag         3
#define MiSceneActionInfo_action_value_tag       4
#define MiSceneActionInfo_model_tag              5
#define MiSceneActionInfo_did_tag                6
#define MiSceneActionInfo_device_name_tag        7
#define MiSceneDeleteParam_scene_id_tag          1
#define MiSceneDeleteParam_mid_tag               2
#define MiSceneLaunchInfo_launch_type_tag        1
#define MiSceneLaunchInfo_launch_name_tag        2
#define MiSceneLaunchInfo_model_tag              3
#define MiSceneLaunchInfo_did_tag                4
#define MiSceneLaunchInfo_event_str_tag          5
#define MiSceneLaunchInfo_event_value_tag        6
#define MiSceneInfo_scene_id_tag                 1
#define MiSceneInfo_mid_tag                      2
#define MiSceneInfo_name_tag                     3
#define MiSceneInfo_launchs_tag                  4
#define MiSceneInfo_actions_tag                  5
#define MiSceneInfo_enable_tag                   6
#define MiSceneList_mi_scene_infos_tag           1

/* Struct field encoding specification for nanopb */
extern const pb_field_t MiSceneLaunchInfo_fields[7];
extern const pb_field_t MiSceneActionInfo_fields[8];
extern const pb_field_t MiSceneInfo_fields[7];
extern const pb_field_t MiSceneList_fields[2];
extern const pb_field_t MiSceneDeleteParam_fields[3];

/* Maximum encoded size of messages (where known) */
#define MiSceneLaunchInfo_size                   191
#define MiSceneActionInfo_size                   273
#define MiSceneInfo_size                         1160
#define MiSceneList_size                         5815
#define MiSceneDeleteParam_size                  33

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MISCENE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
