/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Wed Oct 17 21:28:56 2018. */

#include "Notification.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Notification_fields[3] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, Notification, type, type, 0),
    PB_FIELD(  2, BYTES   , REQUIRED, STATIC  , OTHER, Notification, val, type, 0),
    PB_LAST_FIELD
};

const pb_field_t Telephony_fields[4] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, Telephony, status, status, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, Telephony, number, status, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, STATIC  , OTHER, Telephony, contact, number, 0),
    PB_LAST_FIELD
};

const pb_field_t SMS_fields[4] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, SMS, sender, sender, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, SMS, content, sender, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, STATIC  , OTHER, SMS, contact, content, 0),
    PB_LAST_FIELD
};

const pb_field_t APP_MESSAGE_fields[5] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, APP_MESSAGE, app_id, app_id, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, APP_MESSAGE, title, app_id, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, STATIC  , OTHER, APP_MESSAGE, text, title, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, STATIC  , OTHER, APP_MESSAGE, sub_text, text, 0),
    PB_LAST_FIELD
};

const pb_field_t NotificationAnswerCallParam_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, NotificationAnswerCallParam, number, number, 0),
    PB_LAST_FIELD
};

const pb_field_t NotificationMuteCallParam_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, NotificationMuteCallParam, number, number, 0),
    PB_LAST_FIELD
};

const pb_field_t NotificationRejectCallParam_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, NotificationRejectCallParam, number, number, 0),
    PB_LAST_FIELD
};

const pb_field_t NotificationSetting_fields[6] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, NotificationSetting, version, version, 0),
    PB_FIELD(  2, BOOL    , REQUIRED, STATIC  , OTHER, NotificationSetting, is_all_open, version, 0),
    PB_FIELD(  3, BOOL    , REQUIRED, STATIC  , OTHER, NotificationSetting, is_ios_ancs_open, is_all_open, 0),
    PB_FIELD(  4, BOOL    , REQUIRED, STATIC  , OTHER, NotificationSetting, is_others_open, is_ios_ancs_open, 0),
    PB_FIELD(  5, MESSAGE , REPEATED, STATIC  , OTHER, NotificationSetting, items, is_others_open, &NotificationSettingItem_fields),
    PB_LAST_FIELD
};

const pb_field_t NotificationSettingItem_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, NotificationSettingItem, app_id, app_id, 0),
    PB_FIELD(  2, BOOL    , REQUIRED, STATIC  , OTHER, NotificationSettingItem, is_open, app_id, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceAlert_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, DeviceAlert, version, version, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, DeviceAlert, type, version, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, DeviceAlert, timeout_ms, type, 0),
    PB_LAST_FIELD
};





/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Notification, val) < 65536 && pb_membersize(NotificationSetting, items[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Notification_Telephony_SMS_APP_MESSAGE_NotificationAnswerCallParam_NotificationRejectCallParam_NotificationSetting_NotificationSettingItem_DeviceAlert)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for Notification.val is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
