/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Fri Nov 09 11:31:46 2018. */

#include "PhoneApp.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t PhoneAppInfo_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, PhoneAppInfo, type, type, 0),
    PB_FIELD(  2, UENUM   , OPTIONAL, STATIC  , OTHER, PhoneAppInfo, appType, type, 0),
    PB_LAST_FIELD
};

const pb_field_t AppForegroundEnterParam_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t AppForegroundExitParam_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t AppStatus_fields[3] = {
    PB_FIELD(  1, BOOL    , REQUIRED, STATIC  , FIRST, AppStatus, foreground, foreground, 0),
    PB_FIELD(  2, UENUM   , OPTIONAL, STATIC  , OTHER, AppStatus, lifecycle, foreground, 0),
    PB_LAST_FIELD
};




/* @@protoc_insertion_point(eof) */
