/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Fri Nov 09 11:31:46 2018. */

#ifndef PB_PHONEAPP_PB_H_INCLUDED
#define PB_PHONEAPP_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _PhoneAPPType {
    PhoneAPPType_RyHeyPlus = 0,
    PhoneAPPType_Mijia = 1
} PhoneAPPType;
#define _PhoneAPPType_MIN PhoneAPPType_RyHeyPlus
#define _PhoneAPPType_MAX PhoneAPPType_Mijia
#define _PhoneAPPType_ARRAYSIZE ((PhoneAPPType)(PhoneAPPType_Mijia+1))

typedef enum _PhoneAPPLifeCycleType {
    PhoneAPPLifeCycleType_foreground = 1,
    PhoneAPPLifeCycleType_background = 2,
    PhoneAPPLifeCycleType_destroyed = 3
} PhoneAPPLifeCycleType;
#define _PhoneAPPLifeCycleType_MIN PhoneAPPLifeCycleType_foreground
#define _PhoneAPPLifeCycleType_MAX PhoneAPPLifeCycleType_destroyed
#define _PhoneAPPLifeCycleType_ARRAYSIZE ((PhoneAPPLifeCycleType)(PhoneAPPLifeCycleType_destroyed+1))

/* Struct definitions */
typedef struct _AppForegroundEnterParam {
    char dummy_field;
/* @@protoc_insertion_point(struct:AppForegroundEnterParam) */
} AppForegroundEnterParam;

typedef struct _AppForegroundExitParam {
    char dummy_field;
/* @@protoc_insertion_point(struct:AppForegroundExitParam) */
} AppForegroundExitParam;

typedef struct _AppStatus {
    bool foreground;
    bool has_lifecycle;
    PhoneAPPLifeCycleType lifecycle;
/* @@protoc_insertion_point(struct:AppStatus) */
} AppStatus;

typedef struct _PhoneAppInfo {
    int32_t type;
    bool has_appType;
    PhoneAPPType appType;
/* @@protoc_insertion_point(struct:PhoneAppInfo) */
} PhoneAppInfo;

/* Default values for struct fields */

/* Initializer values for message structs */
#define PhoneAppInfo_init_default                {0, false, (PhoneAPPType)0}
#define AppForegroundEnterParam_init_default     {0}
#define AppForegroundExitParam_init_default      {0}
#define AppStatus_init_default                   {0, false, (PhoneAPPLifeCycleType)0}
#define PhoneAppInfo_init_zero                   {0, false, (PhoneAPPType)0}
#define AppForegroundEnterParam_init_zero        {0}
#define AppForegroundExitParam_init_zero         {0}
#define AppStatus_init_zero                      {0, false, (PhoneAPPLifeCycleType)0}

/* Field tags (for use in manual encoding/decoding) */
#define AppStatus_foreground_tag                 1
#define AppStatus_lifecycle_tag                  2
#define PhoneAppInfo_type_tag                    1
#define PhoneAppInfo_appType_tag                 2

/* Struct field encoding specification for nanopb */
extern const pb_field_t PhoneAppInfo_fields[3];
extern const pb_field_t AppForegroundEnterParam_fields[1];
extern const pb_field_t AppForegroundExitParam_fields[1];
extern const pb_field_t AppStatus_fields[3];

/* Maximum encoded size of messages (where known) */
#define PhoneAppInfo_size                        13
#define AppForegroundEnterParam_size             0
#define AppForegroundExitParam_size              0
#define AppStatus_size                           4

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define PHONEAPP_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
