/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Thu Nov 15 11:03:20 2018. */

#include "Property.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t PropSetParam_fields[3] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, PropSetParam, prop_id, prop_id, 0),
    PB_FIELD(  2, BYTES   , REQUIRED, STATIC  , OTHER, PropSetParam, prop_val, prop_id, 0),
    PB_LAST_FIELD
};

const pb_field_t PropGetParam_fields[2] = {
    PB_FIELD(  1, UENUM   , REPEATED, STATIC  , FIRST, PropGetParam, prop_id, prop_id, 0),
    PB_LAST_FIELD
};

const pb_field_t PropGetResult_fields[2] = {
    PB_FIELD(  1, BYTES   , REPEATED, STATIC  , FIRST, PropGetResult, prop_val, prop_val, 0),
    PB_LAST_FIELD
};

const pb_field_t SportPedoCurrentStepsPropVal_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SportPedoCurrentStepsPropVal, steps, steps, 0),
    PB_LAST_FIELD
};

const pb_field_t HealthLastHeartRatePropVal_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, HealthLastHeartRatePropVal, rate, rate, 0),
    PB_FIELD(  2, INT64   , REQUIRED, STATIC  , OTHER, HealthLastHeartRatePropVal, time, rate, 0),
    PB_LAST_FIELD
};

const pb_field_t HealthRestingHeartRatePropVal_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, HealthRestingHeartRatePropVal, rate, rate, 0),
    PB_LAST_FIELD
};

const pb_field_t HealthSettingHeartRateAutoPropVal_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, HealthSettingHeartRateAutoPropVal, enable, enable, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, HealthSettingHeartRateAutoPropVal, interval, enable, 0),
    PB_LAST_FIELD
};

const pb_field_t HealthSettingScienceSleepPropVal_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, HealthSettingScienceSleepPropVal, enable, enable, 0),
    PB_LAST_FIELD
};

const pb_field_t HealthSettingSitAlertPropVal_fields[9] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, HealthSettingSitAlertPropVal, start_time_hour, start_time_hour, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, HealthSettingSitAlertPropVal, start_time_minute, start_time_hour, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, HealthSettingSitAlertPropVal, end_time_hour, start_time_minute, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, HealthSettingSitAlertPropVal, end_time_minute, end_time_hour, 0),
    PB_FIELD(  5, INT32   , OPTIONAL, STATIC  , OTHER, HealthSettingSitAlertPropVal, forbid_start_time_hour, end_time_minute, 0),
    PB_FIELD(  6, INT32   , OPTIONAL, STATIC  , OTHER, HealthSettingSitAlertPropVal, forbid_start_time_minute, forbid_start_time_hour, 0),
    PB_FIELD(  7, INT32   , OPTIONAL, STATIC  , OTHER, HealthSettingSitAlertPropVal, forbid_end_time_hour, forbid_start_time_minute, 0),
    PB_FIELD(  8, INT32   , OPTIONAL, STATIC  , OTHER, HealthSettingSitAlertPropVal, forbid_end_time_minute, forbid_end_time_hour, 0),
    PB_LAST_FIELD
};

const pb_field_t HealthSettingSleepAlertPropVal_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, HealthSettingSleepAlertPropVal, sleep_time_hour, sleep_time_hour, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, HealthSettingSleepAlertPropVal, sleep_time_minute, sleep_time_hour, 0),
    PB_FIELD(  3, UENUM   , REPEATED, STATIC  , OTHER, HealthSettingSleepAlertPropVal, repeats, sleep_time_minute, 0),
    PB_LAST_FIELD
};

const pb_field_t HealthTargetStepPropVal_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, HealthTargetStepPropVal, step, step, 0),
    PB_LAST_FIELD
};

const pb_field_t HealthCurrentCaloriesPropVal_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, HealthCurrentCaloriesPropVal, cal, cal, 0),
    PB_LAST_FIELD
};

const pb_field_t HealthCurrentDistancePropVal_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, HealthCurrentDistancePropVal, dis, dis, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceRemainingPowerPropVal_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, DeviceRemainingPowerPropVal, power, power, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceLanguagePropVal_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, DeviceLanguagePropVal, type, type, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceBleCfg_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, DeviceBleCfg, peripheral_max_link, peripheral_max_link, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, DeviceBleCfg, is_mi_pc_enabled, peripheral_max_link, 0),    
    PB_LAST_FIELD
};

const pb_field_t DeviceSettingRaiseToWakePropVal_fields[6] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, DeviceSettingRaiseToWakePropVal, enable, enable, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, DeviceSettingRaiseToWakePropVal, start_time_hour, enable, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, DeviceSettingRaiseToWakePropVal, start_time_minute, start_time_hour, 0),
    PB_FIELD(  4, INT32   , OPTIONAL, STATIC  , OTHER, DeviceSettingRaiseToWakePropVal, end_time_hour, start_time_minute, 0),
    PB_FIELD(  5, INT32   , OPTIONAL, STATIC  , OTHER, DeviceSettingRaiseToWakePropVal, end_time_minute, end_time_hour, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceSettingHomeVibratePropVal_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, DeviceSettingHomeVibratePropVal, enable, enable, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceSettingCardSwipingPropVal_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, DeviceSettingCardSwipingPropVal, enable, enable, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceSettingDoNotDisturbPropVal_fields[6] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, DeviceSettingDoNotDisturbPropVal, mode, mode, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, STATIC  , OTHER, DeviceSettingDoNotDisturbPropVal, durations, mode, &DeviceSettingDoNotDisturbPropVal_DndDuration_fields),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, DeviceSettingDoNotDisturbPropVal, raise_to_wake, durations, 0),
    PB_FIELD(  4, INT32   , OPTIONAL, STATIC  , OTHER, DeviceSettingDoNotDisturbPropVal, home_vibrate, raise_to_wake, 0),
    PB_FIELD(  5, INT32   , OPTIONAL, STATIC  , OTHER, DeviceSettingDoNotDisturbPropVal, lunch_mode_enable, home_vibrate, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceSettingDoNotDisturbPropVal_DndDuration_fields[6] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, DeviceSettingDoNotDisturbPropVal_DndDuration, start_time_hour, start_time_hour, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, DeviceSettingDoNotDisturbPropVal_DndDuration, start_time_minute, start_time_hour, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, DeviceSettingDoNotDisturbPropVal_DndDuration, end_time_hour, start_time_minute, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, DeviceSettingDoNotDisturbPropVal_DndDuration, end_time_minute, end_time_hour, 0),
    PB_FIELD(  5, STRING  , REQUIRED, STATIC  , OTHER, DeviceSettingDoNotDisturbPropVal_DndDuration, tag, end_time_minute, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceSettingGoalRemindPropVal_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, DeviceSettingGoalRemindPropVal, enable, enable, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceSettingWearHabitPropVal_fields[2] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, DeviceSettingWearHabitPropVal, wear_habit, wear_habit, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceSettingSurfaceBatteryPropVal_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, DeviceSettingSurfaceBatteryPropVal, enable, enable, 0),
    PB_LAST_FIELD
};

const pb_field_t NotificationSettingMsgRedPointPropVal_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, NotificationSettingMsgRedPointPropVal, enable, enable, 0),
    PB_LAST_FIELD
};

const pb_field_t NotificationSettingRepeatPropVal_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, NotificationSettingRepeatPropVal, times, times, 0),
    PB_LAST_FIELD
};

const pb_field_t PersonalGenderPropVal_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, PersonalGenderPropVal, gender, gender, 0),
    PB_LAST_FIELD
};

const pb_field_t PersonalBirthPropVal_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, PersonalBirthPropVal, year, year, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, PersonalBirthPropVal, month, year, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, PersonalBirthPropVal, day, month, 0),
    PB_LAST_FIELD
};

const pb_field_t PersonalHeightPropVal_fields[3] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, PersonalHeightPropVal, height, height, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, PersonalHeightPropVal, unit, height, 0),
    PB_LAST_FIELD
};

const pb_field_t PersonalWeightPropVal_fields[3] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, PersonalWeightPropVal, weight, weight, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, PersonalWeightPropVal, unit, weight, 0),
    PB_LAST_FIELD
};

const pb_field_t UnlockTypePropVal_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, UnlockTypePropVal, type, type, 0),
    PB_LAST_FIELD
};








/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(DeviceSettingDoNotDisturbPropVal, durations[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_PropSetParam_PropGetParam_PropGetResult_SportPedoCurrentStepsPropVal_HealthLastHeartRatePropVal_HealthRestingHeartRatePropVal_HealthSettingHeartRateAutoPropVal_HealthSettingScienceSleepPropVal_HealthSettingSitAlertPropVal_HealthSettingSleepAlertPropVal_HealthTargetStepPropVal_HealthCurrentCaloriesPropVal_HealthCurrentDistancePropVal_DeviceRemainingPowerPropVal_DeviceSettingRaiseToWakePropVal_DeviceSettingHomeVibratePropVal_DeviceSettingCardSwipingPropVal_DeviceSettingDoNotDisturbPropVal_DeviceSettingDoNotDisturbPropVal_DndDuration_DeviceSettingGoalRemindPropVal_DeviceSettingWearHabitPropVal_NotificationSettingMsgRedPointPropVal_NotificationSettingRepeatPropVal_PersonalGenderPropVal_PersonalBirthPropVal_PersonalHeightPropVal_PersonalWeightPropVal_UnlockTypePropVal)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(DeviceSettingDoNotDisturbPropVal, durations[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_PropSetParam_PropGetParam_PropGetResult_SportPedoCurrentStepsPropVal_HealthLastHeartRatePropVal_HealthRestingHeartRatePropVal_HealthSettingHeartRateAutoPropVal_HealthSettingScienceSleepPropVal_HealthSettingSitAlertPropVal_HealthSettingSleepAlertPropVal_HealthTargetStepPropVal_HealthCurrentCaloriesPropVal_HealthCurrentDistancePropVal_DeviceRemainingPowerPropVal_DeviceSettingRaiseToWakePropVal_DeviceSettingHomeVibratePropVal_DeviceSettingCardSwipingPropVal_DeviceSettingDoNotDisturbPropVal_DeviceSettingDoNotDisturbPropVal_DndDuration_DeviceSettingGoalRemindPropVal_DeviceSettingWearHabitPropVal_NotificationSettingMsgRedPointPropVal_NotificationSettingRepeatPropVal_PersonalGenderPropVal_PersonalBirthPropVal_PersonalHeightPropVal_PersonalWeightPropVal_UnlockTypePropVal)
#endif


/* @@protoc_insertion_point(eof) */
