/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Thu Nov 15 11:03:20 2018. */

#ifndef PB_PROPERTY_PB_H_INCLUDED
#define PB_PROPERTY_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _PROP_ID {
    PROP_ID_SPORT_PEDO_CURRENT_STEPS = 0,
    PROP_ID_HEALTH_LAST_HEART_RATE = 1000,
    PROP_ID_HEALTH_SETTING_HEART_RATE_AUTO = 1001,
    PROP_ID_HEALTH_SETTING_SIT_ALERT = 1002,
    PROP_ID_HEALTH_SETTING_SLEEP_ALERT = 1003,
    PROP_ID_HEALTH_TARGET_STEP = 1004,
    PROP_ID_HEALTH_SETTING_SCIENCE_SLEEP = 1005,
    PROP_ID_HEALTH_RESTING_HEART_RATE = 1006,
    PROP_ID_HEALTH_CURRENT_CALORIES = 1007,
    PROP_ID_HEALTH_CURRENT_DISTANCE = 1008,
    PROP_ID_HEALTH_SETTING_GOAL_REMIND = 1009,
    PROP_ID_DEVICE_REMAINING_POWER = 2001,
    PROP_ID_DEVICE_SETTING_RAISE_TO_WAKE = 2002,
    PROP_ID_DEVICE_SETTING_UNLOCK = 2003,
    PROP_ID_DEVICE_SETTING_HOME_VIBRATE = 2004,
    PROP_ID_DEVICE_SETTING_CARD_SWIPING = 2005,
    PROP_ID_DEVICE_SETTING_DO_NOT_DISTURB = 2006,
    PROP_ID_DEVICE_SETTING_WEAR_HABIT = 2007,
	PROP_ID_DEVICE_SETTING_SURFACE_BATTERY = 2008,
    PROP_ID_DEVICE_LANGUAGE = 2011,
    PROP_ID_DEVICE_BLE_CFG = 2100,
    PROP_ID_NOTIFICATION_SETTING_MSG_RED_POINT = 3001,
    PROP_ID_NOTIFICATION_SETTING_REPEAT = 3002,
    PROP_ID_PERSONAL_GENDER = 4001,
    PROP_ID_PERSONAL_BIRTH = 4002,
    PROP_ID_PERSONAL_HEIGHT = 4003,
    PROP_ID_PERSONAL_WEIGHT = 4004
} PROP_ID;
#define _PROP_ID_MIN PROP_ID_SPORT_PEDO_CURRENT_STEPS
#define _PROP_ID_MAX PROP_ID_PERSONAL_WEIGHT
#define _PROP_ID_ARRAYSIZE ((PROP_ID)(PROP_ID_PERSONAL_WEIGHT+1))

typedef enum _HealthSettingSleepAlertPropVal_RepeatType {
    HealthSettingSleepAlertPropVal_RepeatType_NEVER = 0,
    HealthSettingSleepAlertPropVal_RepeatType_MONDAY = 1,
    HealthSettingSleepAlertPropVal_RepeatType_TUESDAY = 2,
    HealthSettingSleepAlertPropVal_RepeatType_WEDNESDAY = 3,
    HealthSettingSleepAlertPropVal_RepeatType_THURSDAY = 4,
    HealthSettingSleepAlertPropVal_RepeatType_FRIDAY = 5,
    HealthSettingSleepAlertPropVal_RepeatType_SATURDAY = 6,
    HealthSettingSleepAlertPropVal_RepeatType_SUNDAY = 7,
    HealthSettingSleepAlertPropVal_RepeatType_WORKDAY = 8
} HealthSettingSleepAlertPropVal_RepeatType;
#define _HealthSettingSleepAlertPropVal_RepeatType_MIN HealthSettingSleepAlertPropVal_RepeatType_NEVER
#define _HealthSettingSleepAlertPropVal_RepeatType_MAX HealthSettingSleepAlertPropVal_RepeatType_WORKDAY
#define _HealthSettingSleepAlertPropVal_RepeatType_ARRAYSIZE ((HealthSettingSleepAlertPropVal_RepeatType)(HealthSettingSleepAlertPropVal_RepeatType_WORKDAY+1))

typedef enum _DeviceSettingDoNotDisturbPropVal_DndMode {
    DeviceSettingDoNotDisturbPropVal_DndMode_DISABLE = 0,
    DeviceSettingDoNotDisturbPropVal_DndMode_SMART = 1,
    DeviceSettingDoNotDisturbPropVal_DndMode_TIMING = 2
} DeviceSettingDoNotDisturbPropVal_DndMode;
#define _DeviceSettingDoNotDisturbPropVal_DndMode_MIN DeviceSettingDoNotDisturbPropVal_DndMode_DISABLE
#define _DeviceSettingDoNotDisturbPropVal_DndMode_MAX DeviceSettingDoNotDisturbPropVal_DndMode_TIMING
#define _DeviceSettingDoNotDisturbPropVal_DndMode_ARRAYSIZE ((DeviceSettingDoNotDisturbPropVal_DndMode)(DeviceSettingDoNotDisturbPropVal_DndMode_TIMING+1))

typedef enum _DeviceSettingWearHabitPropVal_WearType {
    DeviceSettingWearHabitPropVal_WearType_LEFT_HAND = 1,
    DeviceSettingWearHabitPropVal_WearType_RIGTH_HAND = 2,
    DeviceSettingWearHabitPropVal_WearType_AUTO_IDENTIFICATION = 3
} DeviceSettingWearHabitPropVal_WearType;
#define _DeviceSettingWearHabitPropVal_WearType_MIN DeviceSettingWearHabitPropVal_WearType_LEFT_HAND
#define _DeviceSettingWearHabitPropVal_WearType_MAX DeviceSettingWearHabitPropVal_WearType_AUTO_IDENTIFICATION
#define _DeviceSettingWearHabitPropVal_WearType_ARRAYSIZE ((DeviceSettingWearHabitPropVal_WearType)(DeviceSettingWearHabitPropVal_WearType_AUTO_IDENTIFICATION+1))

typedef enum _PersonalHeightPropVal_Unit {
    PersonalHeightPropVal_Unit_CM = 0
} PersonalHeightPropVal_Unit;
#define _PersonalHeightPropVal_Unit_MIN PersonalHeightPropVal_Unit_CM
#define _PersonalHeightPropVal_Unit_MAX PersonalHeightPropVal_Unit_CM
#define _PersonalHeightPropVal_Unit_ARRAYSIZE ((PersonalHeightPropVal_Unit)(PersonalHeightPropVal_Unit_CM+1))

typedef enum _PersonalWeightPropVal_Unit {
    PersonalWeightPropVal_Unit_KG = 0
} PersonalWeightPropVal_Unit;
#define _PersonalWeightPropVal_Unit_MIN PersonalWeightPropVal_Unit_KG
#define _PersonalWeightPropVal_Unit_MAX PersonalWeightPropVal_Unit_KG
#define _PersonalWeightPropVal_Unit_ARRAYSIZE ((PersonalWeightPropVal_Unit)(PersonalWeightPropVal_Unit_KG+1))

/* Struct definitions */
typedef struct _DeviceRemainingPowerPropVal {
    int32_t power;
/* @@protoc_insertion_point(struct:DeviceRemainingPowerPropVal) */
} DeviceRemainingPowerPropVal;

typedef struct _DeviceBleCfg {
    int32_t peripheral_max_link;
    int32_t is_mi_pc_enabled;
/* @@protoc_insertion_point(struct:DeviceBleCfg) */
} DeviceBleCfg;

typedef struct _DeviceLanguagePropVal {
    int32_t type;
/* @@protoc_insertion_point(struct:DeviceLanguagePropVal) */
} DeviceLanguagePropVal;

typedef struct _DeviceSettingCardSwipingPropVal {
    int32_t enable;
/* @@protoc_insertion_point(struct:DeviceSettingCardSwipingPropVal) */
} DeviceSettingCardSwipingPropVal;

typedef struct _DeviceSettingDoNotDisturbPropVal_DndDuration {
    int32_t start_time_hour;
    int32_t start_time_minute;
    int32_t end_time_hour;
    int32_t end_time_minute;
    char tag[20];
/* @@protoc_insertion_point(struct:DeviceSettingDoNotDisturbPropVal_DndDuration) */
} DeviceSettingDoNotDisturbPropVal_DndDuration;

typedef struct _DeviceSettingGoalRemindPropVal {
    int32_t enable;
/* @@protoc_insertion_point(struct:DeviceSettingGoalRemindPropVal) */
} DeviceSettingGoalRemindPropVal;

typedef struct _DeviceSettingHomeVibratePropVal {
    int32_t enable;
/* @@protoc_insertion_point(struct:DeviceSettingHomeVibratePropVal) */
} DeviceSettingHomeVibratePropVal;

typedef struct _DeviceSettingRaiseToWakePropVal {
    int32_t enable;
    bool has_start_time_hour;
    int32_t start_time_hour;
    bool has_start_time_minute;
    int32_t start_time_minute;
    bool has_end_time_hour;
    int32_t end_time_hour;
    bool has_end_time_minute;
    int32_t end_time_minute;
/* @@protoc_insertion_point(struct:DeviceSettingRaiseToWakePropVal) */
} DeviceSettingRaiseToWakePropVal;

typedef struct _DeviceSettingWearHabitPropVal {
    DeviceSettingWearHabitPropVal_WearType wear_habit;
/* @@protoc_insertion_point(struct:DeviceSettingWearHabitPropVal) */
} DeviceSettingWearHabitPropVal;

typedef struct _DeviceSettingSurfaceBatteryPropVal {
    int32_t enable;
/* @@protoc_insertion_point(struct:DeviceSettingSurfaceBatteryPropVal) */
} DeviceSettingSurfaceBatteryPropVal;

typedef struct _HealthCurrentCaloriesPropVal {
    int32_t cal;
/* @@protoc_insertion_point(struct:HealthCurrentCaloriesPropVal) */
} HealthCurrentCaloriesPropVal;

typedef struct _HealthCurrentDistancePropVal {
    int32_t dis;
/* @@protoc_insertion_point(struct:HealthCurrentDistancePropVal) */
} HealthCurrentDistancePropVal;

typedef struct _HealthLastHeartRatePropVal {
    int32_t rate;
    int64_t time;
/* @@protoc_insertion_point(struct:HealthLastHeartRatePropVal) */
} HealthLastHeartRatePropVal;

typedef struct _HealthRestingHeartRatePropVal {
    int32_t rate;
/* @@protoc_insertion_point(struct:HealthRestingHeartRatePropVal) */
} HealthRestingHeartRatePropVal;

typedef struct _HealthSettingHeartRateAutoPropVal {
    int32_t enable;
    bool has_interval;
    int32_t interval;
/* @@protoc_insertion_point(struct:HealthSettingHeartRateAutoPropVal) */
} HealthSettingHeartRateAutoPropVal;

typedef struct _HealthSettingScienceSleepPropVal {
    int32_t enable;
/* @@protoc_insertion_point(struct:HealthSettingScienceSleepPropVal) */
} HealthSettingScienceSleepPropVal;

typedef struct _HealthSettingSitAlertPropVal {
    int32_t start_time_hour;
    int32_t start_time_minute;
    int32_t end_time_hour;
    int32_t end_time_minute;
    bool has_forbid_start_time_hour;
    int32_t forbid_start_time_hour;
    bool has_forbid_start_time_minute;
    int32_t forbid_start_time_minute;
    bool has_forbid_end_time_hour;
    int32_t forbid_end_time_hour;
    bool has_forbid_end_time_minute;
    int32_t forbid_end_time_minute;
/* @@protoc_insertion_point(struct:HealthSettingSitAlertPropVal) */
} HealthSettingSitAlertPropVal;

typedef struct _HealthSettingSleepAlertPropVal {
    int32_t sleep_time_hour;
    int32_t sleep_time_minute;
    pb_size_t repeats_count;
    HealthSettingSleepAlertPropVal_RepeatType repeats[8];
/* @@protoc_insertion_point(struct:HealthSettingSleepAlertPropVal) */
} HealthSettingSleepAlertPropVal;

typedef struct _HealthTargetStepPropVal {
    int32_t step;
/* @@protoc_insertion_point(struct:HealthTargetStepPropVal) */
} HealthTargetStepPropVal;

typedef struct _NotificationSettingMsgRedPointPropVal {
    int32_t enable;
/* @@protoc_insertion_point(struct:NotificationSettingMsgRedPointPropVal) */
} NotificationSettingMsgRedPointPropVal;

typedef struct _NotificationSettingRepeatPropVal {
    int32_t times;
/* @@protoc_insertion_point(struct:NotificationSettingRepeatPropVal) */
} NotificationSettingRepeatPropVal;

typedef struct _PersonalBirthPropVal {
    int32_t year;
    int32_t month;
    int32_t day;
/* @@protoc_insertion_point(struct:PersonalBirthPropVal) */
} PersonalBirthPropVal;

typedef struct _PersonalGenderPropVal {
    int32_t gender;
/* @@protoc_insertion_point(struct:PersonalGenderPropVal) */
} PersonalGenderPropVal;

typedef struct _PersonalHeightPropVal {
    float height;
    PersonalHeightPropVal_Unit unit;
/* @@protoc_insertion_point(struct:PersonalHeightPropVal) */
} PersonalHeightPropVal;

typedef struct _PersonalWeightPropVal {
    float weight;
    PersonalWeightPropVal_Unit unit;
/* @@protoc_insertion_point(struct:PersonalWeightPropVal) */
} PersonalWeightPropVal;

typedef struct _PropGetParam {
    pb_size_t prop_id_count;
    PROP_ID prop_id[20];
/* @@protoc_insertion_point(struct:PropGetParam) */
} PropGetParam;

typedef PB_BYTES_ARRAY_T(80) PropGetResult_prop_val_t;
typedef struct _PropGetResult {
    pb_size_t prop_val_count;
    PropGetResult_prop_val_t prop_val[20];
/* @@protoc_insertion_point(struct:PropGetResult) */
} PropGetResult;

typedef PB_BYTES_ARRAY_T(80) PropSetParam_prop_val_t;
typedef struct _PropSetParam {
    PROP_ID prop_id;
    PropSetParam_prop_val_t prop_val;
/* @@protoc_insertion_point(struct:PropSetParam) */
} PropSetParam;

typedef struct _SportPedoCurrentStepsPropVal {
    int32_t steps;
/* @@protoc_insertion_point(struct:SportPedoCurrentStepsPropVal) */
} SportPedoCurrentStepsPropVal;

typedef struct _UnlockTypePropVal {
    int32_t type;
/* @@protoc_insertion_point(struct:UnlockTypePropVal) */
} UnlockTypePropVal;

typedef struct _DeviceSettingDoNotDisturbPropVal {
    DeviceSettingDoNotDisturbPropVal_DndMode mode;
    pb_size_t durations_count;
    DeviceSettingDoNotDisturbPropVal_DndDuration durations[5];
    bool has_raise_to_wake;
    int32_t raise_to_wake;
    bool has_home_vibrate;
    int32_t home_vibrate;
    bool has_lunch_mode_enable;
    int32_t lunch_mode_enable;
/* @@protoc_insertion_point(struct:DeviceSettingDoNotDisturbPropVal) */
} DeviceSettingDoNotDisturbPropVal;

/* Default values for struct fields */

/* Initializer values for message structs */
#define PropSetParam_init_default                {(PROP_ID)0, {0, {0}}}
#define PropGetParam_init_default                {0, {(PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0}}
#define PropGetResult_init_default               {0, {{0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}}}
#define SportPedoCurrentStepsPropVal_init_default {0}
#define HealthLastHeartRatePropVal_init_default  {0, 0}
#define HealthRestingHeartRatePropVal_init_default {0}
#define HealthSettingHeartRateAutoPropVal_init_default {0, false, 0}
#define HealthSettingScienceSleepPropVal_init_default {0}
#define HealthSettingSitAlertPropVal_init_default {0, 0, 0, 0, false, 0, false, 0, false, 0, false, 0}
#define HealthSettingSleepAlertPropVal_init_default {0, 0, 0, {(HealthSettingSleepAlertPropVal_RepeatType)0, (HealthSettingSleepAlertPropVal_RepeatType)0, (HealthSettingSleepAlertPropVal_RepeatType)0, (HealthSettingSleepAlertPropVal_RepeatType)0, (HealthSettingSleepAlertPropVal_RepeatType)0, (HealthSettingSleepAlertPropVal_RepeatType)0, (HealthSettingSleepAlertPropVal_RepeatType)0, (HealthSettingSleepAlertPropVal_RepeatType)0}}
#define HealthTargetStepPropVal_init_default     {0}
#define HealthCurrentCaloriesPropVal_init_default {0}
#define HealthCurrentDistancePropVal_init_default {0}
#define DeviceRemainingPowerPropVal_init_default {0}
#define DeviceBleCfg_init_default {0, 0}
#define DeviceLanguagePropVal_init_default {0}
#define DeviceSettingRaiseToWakePropVal_init_default {0, false, 0, false, 0, false, 0, false, 0}
#define DeviceSettingHomeVibratePropVal_init_default {0}
#define DeviceSettingCardSwipingPropVal_init_default {0}
#define DeviceSettingDoNotDisturbPropVal_init_default {(DeviceSettingDoNotDisturbPropVal_DndMode)0, 0, {DeviceSettingDoNotDisturbPropVal_DndDuration_init_default, DeviceSettingDoNotDisturbPropVal_DndDuration_init_default, DeviceSettingDoNotDisturbPropVal_DndDuration_init_default, DeviceSettingDoNotDisturbPropVal_DndDuration_init_default, DeviceSettingDoNotDisturbPropVal_DndDuration_init_default}, false, 0, false, 0, false, 0}
#define DeviceSettingDoNotDisturbPropVal_DndDuration_init_default {0, 0, 0, 0, ""}
#define DeviceSettingGoalRemindPropVal_init_default {0}
#define DeviceSettingWearHabitPropVal_init_default {(DeviceSettingWearHabitPropVal_WearType)0}
#define DeviceSettingSurfaceBatteryPropVal_init_default {0}
#define NotificationSettingMsgRedPointPropVal_init_default {0}
#define NotificationSettingRepeatPropVal_init_default {0}
#define PersonalGenderPropVal_init_default       {0}
#define PersonalBirthPropVal_init_default        {0, 0, 0}
#define PersonalHeightPropVal_init_default       {0, (PersonalHeightPropVal_Unit)0}
#define PersonalWeightPropVal_init_default       {0, (PersonalWeightPropVal_Unit)0}
#define UnlockTypePropVal_init_default           {0}
#define PropSetParam_init_zero                   {(PROP_ID)0, {0, {0}}}
#define PropGetParam_init_zero                   {0, {(PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0, (PROP_ID)0}}
#define PropGetResult_init_zero                  {0, {{0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}}}
#define SportPedoCurrentStepsPropVal_init_zero   {0}
#define HealthLastHeartRatePropVal_init_zero     {0, 0}
#define HealthRestingHeartRatePropVal_init_zero  {0}
#define HealthSettingHeartRateAutoPropVal_init_zero {0, false, 0}
#define HealthSettingScienceSleepPropVal_init_zero {0}
#define HealthSettingSitAlertPropVal_init_zero   {0, 0, 0, 0, false, 0, false, 0, false, 0, false, 0}
#define HealthSettingSleepAlertPropVal_init_zero {0, 0, 0, {(HealthSettingSleepAlertPropVal_RepeatType)0, (HealthSettingSleepAlertPropVal_RepeatType)0, (HealthSettingSleepAlertPropVal_RepeatType)0, (HealthSettingSleepAlertPropVal_RepeatType)0, (HealthSettingSleepAlertPropVal_RepeatType)0, (HealthSettingSleepAlertPropVal_RepeatType)0, (HealthSettingSleepAlertPropVal_RepeatType)0, (HealthSettingSleepAlertPropVal_RepeatType)0}}
#define HealthTargetStepPropVal_init_zero        {0}
#define HealthCurrentCaloriesPropVal_init_zero   {0}
#define HealthCurrentDistancePropVal_init_zero   {0}
#define DeviceRemainingPowerPropVal_init_zero    {0}
#define DeviceBleCfg_init_zero                   {0, 0}
#define DeviceLanguagePropVal_init_zero          {0}
#define DeviceSettingRaiseToWakePropVal_init_zero {0, false, 0, false, 0, false, 0, false, 0}
#define DeviceSettingHomeVibratePropVal_init_zero {0}
#define DeviceSettingCardSwipingPropVal_init_zero {0}
#define DeviceSettingDoNotDisturbPropVal_init_zero {(DeviceSettingDoNotDisturbPropVal_DndMode)0, 0, {DeviceSettingDoNotDisturbPropVal_DndDuration_init_zero, DeviceSettingDoNotDisturbPropVal_DndDuration_init_zero, DeviceSettingDoNotDisturbPropVal_DndDuration_init_zero, DeviceSettingDoNotDisturbPropVal_DndDuration_init_zero, DeviceSettingDoNotDisturbPropVal_DndDuration_init_zero}, false, 0, false, 0, false, 0}
#define DeviceSettingDoNotDisturbPropVal_DndDuration_init_zero {0, 0, 0, 0, ""}
#define DeviceSettingGoalRemindPropVal_init_zero {0}
#define DeviceSettingWearHabitPropVal_init_zero  {(DeviceSettingWearHabitPropVal_WearType)0}
#define DeviceSettingSurfaceBatteryPropVal_init_zero {0}
#define NotificationSettingMsgRedPointPropVal_init_zero {0}
#define NotificationSettingRepeatPropVal_init_zero {0}
#define PersonalGenderPropVal_init_zero          {0}
#define PersonalBirthPropVal_init_zero           {0, 0, 0}
#define PersonalHeightPropVal_init_zero          {0, (PersonalHeightPropVal_Unit)0}
#define PersonalWeightPropVal_init_zero          {0, (PersonalWeightPropVal_Unit)0}
#define UnlockTypePropVal_init_zero              {0}

/* Field tags (for use in manual encoding/decoding) */
#define DeviceRemainingPowerPropVal_power_tag    1
#define DeviceBleCfg_peripheral_max_link_tag    1
#define DeviceBleCfg_is_mi_pc_enabled_tag       2
#define DeviceLanguagePropVal_type_tag          1
#define DeviceSettingCardSwipingPropVal_enable_tag 1
#define DeviceSettingDoNotDisturbPropVal_DndDuration_start_time_hour_tag 1
#define DeviceSettingDoNotDisturbPropVal_DndDuration_start_time_minute_tag 2
#define DeviceSettingDoNotDisturbPropVal_DndDuration_end_time_hour_tag 3
#define DeviceSettingDoNotDisturbPropVal_DndDuration_end_time_minute_tag 4
#define DeviceSettingDoNotDisturbPropVal_DndDuration_tag_tag 5
#define DeviceSettingGoalRemindPropVal_enable_tag 1
#define DeviceSettingHomeVibratePropVal_enable_tag 1
#define DeviceSettingRaiseToWakePropVal_enable_tag 1
#define DeviceSettingRaiseToWakePropVal_start_time_hour_tag 2
#define DeviceSettingRaiseToWakePropVal_start_time_minute_tag 3
#define DeviceSettingRaiseToWakePropVal_end_time_hour_tag 4
#define DeviceSettingRaiseToWakePropVal_end_time_minute_tag 5
#define DeviceSettingWearHabitPropVal_wear_habit_tag 1
#define HealthCurrentCaloriesPropVal_cal_tag     1
#define HealthCurrentDistancePropVal_dis_tag     1
#define HealthLastHeartRatePropVal_rate_tag      1
#define HealthLastHeartRatePropVal_time_tag      2
#define HealthRestingHeartRatePropVal_rate_tag   1
#define HealthSettingHeartRateAutoPropVal_enable_tag 1
#define HealthSettingHeartRateAutoPropVal_interval_tag 2
#define HealthSettingScienceSleepPropVal_enable_tag 1
#define HealthSettingSitAlertPropVal_start_time_hour_tag 1
#define HealthSettingSitAlertPropVal_start_time_minute_tag 2
#define HealthSettingSitAlertPropVal_end_time_hour_tag 3
#define HealthSettingSitAlertPropVal_end_time_minute_tag 4
#define HealthSettingSitAlertPropVal_forbid_start_time_hour_tag 5
#define HealthSettingSitAlertPropVal_forbid_start_time_minute_tag 6
#define HealthSettingSitAlertPropVal_forbid_end_time_hour_tag 7
#define HealthSettingSitAlertPropVal_forbid_end_time_minute_tag 8
#define HealthSettingSleepAlertPropVal_sleep_time_hour_tag 1
#define HealthSettingSleepAlertPropVal_sleep_time_minute_tag 2
#define HealthSettingSleepAlertPropVal_repeats_tag 3
#define HealthTargetStepPropVal_step_tag         1
#define NotificationSettingMsgRedPointPropVal_enable_tag 1
#define NotificationSettingRepeatPropVal_times_tag 1
#define PersonalBirthPropVal_year_tag            1
#define PersonalBirthPropVal_month_tag           2
#define PersonalBirthPropVal_day_tag             3
#define PersonalGenderPropVal_gender_tag         1
#define PersonalHeightPropVal_height_tag         1
#define PersonalHeightPropVal_unit_tag           2
#define PersonalWeightPropVal_weight_tag         1
#define PersonalWeightPropVal_unit_tag           2
#define PropGetParam_prop_id_tag                 1
#define PropGetResult_prop_val_tag               1
#define PropSetParam_prop_id_tag                 1
#define PropSetParam_prop_val_tag                2
#define SportPedoCurrentStepsPropVal_steps_tag   1
#define UnlockTypePropVal_type_tag               1
#define DeviceSettingDoNotDisturbPropVal_mode_tag 1
#define DeviceSettingDoNotDisturbPropVal_durations_tag 2
#define DeviceSettingDoNotDisturbPropVal_raise_to_wake_tag 3
#define DeviceSettingDoNotDisturbPropVal_home_vibrate_tag 4
#define DeviceSettingDoNotDisturbPropVal_lunch_mode_enable_tag 5

/* Struct field encoding specification for nanopb */
extern const pb_field_t PropSetParam_fields[3];
extern const pb_field_t PropGetParam_fields[2];
extern const pb_field_t PropGetResult_fields[2];
extern const pb_field_t SportPedoCurrentStepsPropVal_fields[2];
extern const pb_field_t HealthLastHeartRatePropVal_fields[3];
extern const pb_field_t HealthRestingHeartRatePropVal_fields[2];
extern const pb_field_t HealthSettingHeartRateAutoPropVal_fields[3];
extern const pb_field_t HealthSettingScienceSleepPropVal_fields[2];
extern const pb_field_t HealthSettingSitAlertPropVal_fields[9];
extern const pb_field_t HealthSettingSleepAlertPropVal_fields[4];
extern const pb_field_t HealthTargetStepPropVal_fields[2];
extern const pb_field_t HealthCurrentCaloriesPropVal_fields[2];
extern const pb_field_t HealthCurrentDistancePropVal_fields[2];
extern const pb_field_t DeviceRemainingPowerPropVal_fields[2];
extern const pb_field_t DeviceBleCfg_fields[3];
extern const pb_field_t DeviceLanguagePropVal_fields[2];
extern const pb_field_t DeviceSettingRaiseToWakePropVal_fields[6];
extern const pb_field_t DeviceSettingHomeVibratePropVal_fields[2];
extern const pb_field_t DeviceSettingCardSwipingPropVal_fields[2];
extern const pb_field_t DeviceSettingDoNotDisturbPropVal_fields[6];
extern const pb_field_t DeviceSettingDoNotDisturbPropVal_DndDuration_fields[6];
extern const pb_field_t DeviceSettingGoalRemindPropVal_fields[2];
extern const pb_field_t DeviceSettingWearHabitPropVal_fields[2];
extern const pb_field_t DeviceSettingSurfaceBatteryPropVal_fields[2];
extern const pb_field_t NotificationSettingMsgRedPointPropVal_fields[2];
extern const pb_field_t NotificationSettingRepeatPropVal_fields[2];
extern const pb_field_t PersonalGenderPropVal_fields[2];
extern const pb_field_t PersonalBirthPropVal_fields[4];
extern const pb_field_t PersonalHeightPropVal_fields[3];
extern const pb_field_t PersonalWeightPropVal_fields[3];
extern const pb_field_t UnlockTypePropVal_fields[2];

/* Maximum encoded size of messages (where known) */
#define PropSetParam_size                        85
#define PropGetParam_size                        60
#define PropGetResult_size                       1640
#define SportPedoCurrentStepsPropVal_size        11
#define HealthLastHeartRatePropVal_size          22
#define HealthRestingHeartRatePropVal_size       11
#define HealthSettingHeartRateAutoPropVal_size   22
#define HealthSettingScienceSleepPropVal_size    11
#define HealthSettingSitAlertPropVal_size        88
#define HealthSettingSleepAlertPropVal_size      38
#define HealthTargetStepPropVal_size             11
#define HealthCurrentCaloriesPropVal_size        11
#define HealthCurrentDistancePropVal_size        11
#define DeviceRemainingPowerPropVal_size         11
#define DeviceLanguagePropVal_size               11
#define DeviceBleCfg_size                        22
#define DeviceSettingRaiseToWakePropVal_size     55
#define DeviceSettingHomeVibratePropVal_size     11
#define DeviceSettingCardSwipingPropVal_size     11
#define DeviceSettingDoNotDisturbPropVal_size    375
#define DeviceSettingDoNotDisturbPropVal_DndDuration_size 66
#define DeviceSettingGoalRemindPropVal_size      11
#define DeviceSettingWearHabitPropVal_size       2
#define DeviceSettingSurfaceBatteryPropVal_size	 11 
#define NotificationSettingMsgRedPointPropVal_size 11
#define NotificationSettingRepeatPropVal_size    11
#define PersonalGenderPropVal_size               11
#define PersonalBirthPropVal_size                33
#define PersonalHeightPropVal_size               7
#define PersonalWeightPropVal_size               7
#define UnlockTypePropVal_size                   11

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define PROPERTY_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
