/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Wed Oct 17 21:28:24 2018. */

#include "rbp.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t RbpMsg_fields[7] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, RbpMsg, protocol_ver, protocol_ver, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, RbpMsg, cmd, protocol_ver, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, RbpMsg, session_id, cmd, 0),
    PB_ONEOF_FIELD(message,   4, MESSAGE , ONEOF, STATIC  , OTHER, RbpMsg, req, session_id, &RbpMsg_Req_fields),
    PB_ONEOF_FIELD(message,   5, MESSAGE , ONEOF, STATIC  , UNION, RbpMsg, res, session_id, &RbpMsg_Res_fields),
    PB_ONEOF_FIELD(message,   6, MESSAGE , ONEOF, STATIC  , UNION, RbpMsg, ind, session_id, &RbpMsg_Ind_fields),
    PB_LAST_FIELD
};

const pb_field_t RbpMsg_Req_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, RbpMsg_Req, total, total, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, RbpMsg_Req, sn, total, 0),
    PB_FIELD(  3, BYTES   , OPTIONAL, STATIC  , OTHER, RbpMsg_Req, val, sn, 0),
    PB_LAST_FIELD
};

const pb_field_t RbpMsg_Res_fields[5] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, RbpMsg_Res, total, total, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, RbpMsg_Res, sn, total, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, RbpMsg_Res, code, sn, 0),
    PB_FIELD(  4, BYTES   , OPTIONAL, STATIC  , OTHER, RbpMsg_Res, val, code, 0),
    PB_LAST_FIELD
};

const pb_field_t RbpMsg_Ind_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, RbpMsg_Ind, total, total, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, RbpMsg_Ind, sn, total, 0),
    PB_FIELD(  3, BYTES   , OPTIONAL, STATIC  , OTHER, RbpMsg_Ind, val, sn, 0),
    PB_LAST_FIELD
};

const pb_field_t RbpMsg_Int32_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, RbpMsg_Int32, val, val, 0),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(RbpMsg, message.req) < 65536 && pb_membersize(RbpMsg, message.res) < 65536 && pb_membersize(RbpMsg, message.ind) < 65536 && pb_membersize(RbpMsg_Req, val) < 65536 && pb_membersize(RbpMsg_Res, val) < 65536 && pb_membersize(RbpMsg_Ind, val) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_RbpMsg_RbpMsg_Req_RbpMsg_Res_RbpMsg_Ind_RbpMsg_Int32)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for RbpMsg_Ind.val is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
