/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Tue Oct 16 22:32:12 2018. */

#include "Sport.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SportRunStartParam_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SportRunStartParam, session_id, session_id, 0),
    PB_LAST_FIELD
};

const pb_field_t SportRunUpdateParam_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SportRunUpdateParam, session_id, session_id, 0),
    PB_LAST_FIELD
};

const pb_field_t SportRunPauseParam_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SportRunPauseParam, session_id, session_id, 0),
    PB_LAST_FIELD
};

const pb_field_t SportRunResumeParam_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SportRunResumeParam, session_id, session_id, 0),
    PB_LAST_FIELD
};

const pb_field_t SportRunUpdateResult_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SportRunUpdateResult, session_id, session_id, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, SportRunUpdateResult, distance, session_id, 0),
    PB_FIELD(  3, BOOL    , OPTIONAL, STATIC  , OTHER, SportRunUpdateResult, gps_status, distance, 0),
    PB_LAST_FIELD
};

const pb_field_t SportRunStopParam_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SportRunStopParam, session_id, session_id, 0),
    PB_LAST_FIELD
};

const pb_field_t SportRideStartParam_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SportRideStartParam, session_id, session_id, 0),
    PB_LAST_FIELD
};

const pb_field_t SportRideUpdateParam_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SportRideUpdateParam, session_id, session_id, 0),
    PB_LAST_FIELD
};

const pb_field_t SportRidePauseParam_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SportRidePauseParam, session_id, session_id, 0),
    PB_LAST_FIELD
};

const pb_field_t SportRideResumeParam_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SportRideResumeParam, session_id, session_id, 0),
    PB_LAST_FIELD
};

const pb_field_t SportRideUpdateResult_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SportRideUpdateResult, session_id, session_id, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, SportRideUpdateResult, distance, session_id, 0),
    PB_FIELD(  3, BOOL    , OPTIONAL, STATIC  , OTHER, SportRideUpdateResult, gps_status, distance, 0),
    PB_LAST_FIELD
};

const pb_field_t SportRideStopParam_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SportRideStopParam, session_id, session_id, 0),
    PB_LAST_FIELD
};

const pb_field_t SportWalkStartParam_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SportWalkStartParam, session_id, session_id, 0),
    PB_LAST_FIELD
};

const pb_field_t SportWalkUpdateParam_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SportWalkUpdateParam, session_id, session_id, 0),
    PB_LAST_FIELD
};

const pb_field_t SportWalkPauseParam_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SportWalkPauseParam, session_id, session_id, 0),
    PB_LAST_FIELD
};

const pb_field_t SportWalkResumeParam_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SportWalkResumeParam, session_id, session_id, 0),
    PB_LAST_FIELD
};

const pb_field_t SportWalkUpdateResult_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SportWalkUpdateResult, session_id, session_id, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, SportWalkUpdateResult, distance, session_id, 0),
    PB_FIELD(  3, BOOL    , OPTIONAL, STATIC  , OTHER, SportWalkUpdateResult, gps_status, distance, 0),
    PB_LAST_FIELD
};

const pb_field_t SportWalkStopParam_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SportWalkStopParam, session_id, session_id, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
