/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Thu Oct 18 18:13:14 2018. */

#ifndef PB_SURFACE_PB_H_INCLUDED
#define PB_SURFACE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _surfaceResourceType {
    surfaceResourceType_json = 1,
    surfaceResourceType_bmp = 2
} surfaceResourceType;
#define _surfaceResourceType_MIN surfaceResourceType_json
#define _surfaceResourceType_MAX surfaceResourceType_bmp
#define _surfaceResourceType_ARRAYSIZE ((surfaceResourceType)(surfaceResourceType_bmp+1))

/* Struct definitions */
typedef struct _SurfaceDeleteParam {
    int32_t id;
    bool has_ryid;
    int32_t ryid;
/* @@protoc_insertion_point(struct:SurfaceDeleteParam) */
} SurfaceDeleteParam;

typedef struct _SurfaceInfo {
    int32_t id;
    bool is_selected;
    bool has_ryid;
    int32_t ryid;
/* @@protoc_insertion_point(struct:SurfaceInfo) */
} SurfaceInfo;

typedef struct _SurfaceResource {
    surfaceResourceType type;
    char filename[64];
    uint32_t length;
    uint32_t crc;
    bool has_process;
    uint32_t process;
/* @@protoc_insertion_point(struct:SurfaceResource) */
} SurfaceResource;

typedef struct _SurfaceSetCurrentParam {
    int32_t id;
    bool has_ryid;
    int32_t ryid;
/* @@protoc_insertion_point(struct:SurfaceSetCurrentParam) */
} SurfaceSetCurrentParam;

typedef struct _SurfaceAddStartParam {
    int32_t id;
    bool has_ryid;
    int32_t ryid;
    int32_t version;
    pb_size_t resources_count;
    SurfaceResource resources[4];
    bool has_session;
    int32_t session;
/* @@protoc_insertion_point(struct:SurfaceAddStartParam) */
} SurfaceAddStartParam;

typedef struct _SurfaceList {
    pb_size_t surface_infos_count;
    SurfaceInfo surface_infos[6];
/* @@protoc_insertion_point(struct:SurfaceList) */
} SurfaceList;

/* Default values for struct fields */

/* Initializer values for message structs */
#define SurfaceInfo_init_default                 {0, 0, false, 0}
#define SurfaceList_init_default                 {0, {SurfaceInfo_init_default, SurfaceInfo_init_default, SurfaceInfo_init_default, SurfaceInfo_init_default, SurfaceInfo_init_default, SurfaceInfo_init_default}}
#define SurfaceResource_init_default             {(surfaceResourceType)0, "", 0, 0, false, 0}
#define SurfaceDeleteParam_init_default          {0, false, 0}
#define SurfaceSetCurrentParam_init_default      {0, false, 0}
#define SurfaceAddStartParam_init_default        {0, false, 0, 0, 0, {SurfaceResource_init_default, SurfaceResource_init_default, SurfaceResource_init_default, SurfaceResource_init_default}, false, 0}
#define SurfaceInfo_init_zero                    {0, 0, false, 0}
#define SurfaceList_init_zero                    {0, {SurfaceInfo_init_zero, SurfaceInfo_init_zero, SurfaceInfo_init_zero, SurfaceInfo_init_zero, SurfaceInfo_init_zero, SurfaceInfo_init_zero}}
#define SurfaceResource_init_zero                {(surfaceResourceType)0, "", 0, 0, false, 0}
#define SurfaceDeleteParam_init_zero             {0, false, 0}
#define SurfaceSetCurrentParam_init_zero         {0, false, 0}
#define SurfaceAddStartParam_init_zero           {0, false, 0, 0, 0, {SurfaceResource_init_zero, SurfaceResource_init_zero, SurfaceResource_init_zero, SurfaceResource_init_zero}, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define SurfaceDeleteParam_id_tag                1
#define SurfaceDeleteParam_ryid_tag              2
#define SurfaceInfo_id_tag                       1
#define SurfaceInfo_is_selected_tag              2
#define SurfaceInfo_ryid_tag                     3
#define SurfaceResource_type_tag                 1
#define SurfaceResource_filename_tag             2
#define SurfaceResource_length_tag               3
#define SurfaceResource_crc_tag                  4
#define SurfaceResource_process_tag              5
#define SurfaceSetCurrentParam_id_tag            1
#define SurfaceSetCurrentParam_ryid_tag          2
#define SurfaceAddStartParam_id_tag              1
#define SurfaceAddStartParam_ryid_tag            2
#define SurfaceAddStartParam_version_tag         3
#define SurfaceAddStartParam_resources_tag       4
#define SurfaceAddStartParam_session_tag         5
#define SurfaceList_surface_infos_tag            1

/* Struct field encoding specification for nanopb */
extern const pb_field_t SurfaceInfo_fields[4];
extern const pb_field_t SurfaceList_fields[2];
extern const pb_field_t SurfaceResource_fields[6];
extern const pb_field_t SurfaceDeleteParam_fields[3];
extern const pb_field_t SurfaceSetCurrentParam_fields[3];
extern const pb_field_t SurfaceAddStartParam_fields[6];

/* Maximum encoded size of messages (where known) */
#define SurfaceInfo_size                         24
#define SurfaceList_size                         156
#define SurfaceResource_size                     86
#define SurfaceDeleteParam_size                  22
#define SurfaceSetCurrentParam_size              22
#define SurfaceAddStartParam_size                396

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SURFACE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
