/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Thu Oct 18 18:13:14 2018. */

#include "Surface.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SurfaceInfo_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SurfaceInfo, id, id, 0),
    PB_FIELD(  2, BOOL    , REQUIRED, STATIC  , OTHER, SurfaceInfo, is_selected, id, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, SurfaceInfo, ryid, is_selected, 0),
    PB_LAST_FIELD
};

const pb_field_t SurfaceList_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, SurfaceList, surface_infos, surface_infos, &SurfaceInfo_fields),
    PB_LAST_FIELD
};

const pb_field_t SurfaceResource_fields[6] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, SurfaceResource, type, type, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, SurfaceResource, filename, type, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, SurfaceResource, length, filename, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, SurfaceResource, crc, length, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, SurfaceResource, process, crc, 0),
    PB_LAST_FIELD
};

const pb_field_t SurfaceDeleteParam_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SurfaceDeleteParam, id, id, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, SurfaceDeleteParam, ryid, id, 0),
    PB_LAST_FIELD
};

const pb_field_t SurfaceSetCurrentParam_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SurfaceSetCurrentParam, id, id, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, SurfaceSetCurrentParam, ryid, id, 0),
    PB_LAST_FIELD
};

const pb_field_t SurfaceAddStartParam_fields[6] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SurfaceAddStartParam, id, id, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, SurfaceAddStartParam, ryid, id, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, SurfaceAddStartParam, version, ryid, 0),
    PB_FIELD(  4, MESSAGE , REPEATED, STATIC  , OTHER, SurfaceAddStartParam, resources, version, &SurfaceResource_fields),
    PB_FIELD(  5, INT32   , OPTIONAL, STATIC  , OTHER, SurfaceAddStartParam, session, resources, 0),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(SurfaceList, surface_infos[0]) < 65536 && pb_membersize(SurfaceAddStartParam, resources[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_SurfaceInfo_SurfaceList_SurfaceResource_SurfaceDeleteParam_SurfaceSetCurrentParam_SurfaceAddStartParam)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(SurfaceList, surface_infos[0]) < 256 && pb_membersize(SurfaceAddStartParam, resources[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_SurfaceInfo_SurfaceList_SurfaceResource_SurfaceDeleteParam_SurfaceSetCurrentParam_SurfaceAddStartParam)
#endif


/* @@protoc_insertion_point(eof) */
