/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Mon Mar 12 16:32:35 2018. */

#include "Time.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t TimeZoneSet_fields[4] = {
    PB_FIELD(  1, INT32  , REQUIRED, STATIC  , FIRST, TimeZoneSet, utc_time, utc_time, 0),
    PB_FIELD(  2, INT32  , OPTIONAL, STATIC  , OTHER, TimeZoneSet, deviation, utc_time, 0),
    PB_FIELD(  3, INT32  , OPTIONAL, STATIC  , OTHER, TimeZoneSet, daylight, deviation, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
