/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Fri Sep 07 17:30:48 2018. */

#ifndef PB_TRANSIT_PB_H_INCLUDED
#define PB_TRANSIT_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _TransitCreateAck {
    int32_t code;
/* @@protoc_insertion_point(struct:TransitCreateAck) */
} TransitCreateAck;

typedef PB_BYTES_ARRAY_T(18) TransitCreateParam_aid_t;
typedef struct _TransitCreateParam {
    TransitCreateParam_aid_t aid;
    char name[20];
    bool has_city_id;
    char city_id[10];
/* @@protoc_insertion_point(struct:TransitCreateParam) */
} TransitCreateParam;

typedef PB_BYTES_ARRAY_T(18) TransitInfo_aid_t;
typedef PB_BYTES_ARRAY_T(20) TransitInfo_nfc_setting_t;
typedef struct _TransitInfo {
    TransitInfo_aid_t aid;
    char use_city_id[10];
    char use_city_name[30];
    TransitInfo_nfc_setting_t nfc_setting;
/* @@protoc_insertion_point(struct:TransitInfo) */
} TransitInfo;

typedef struct _TransitRechargeAck {
    int32_t code;
/* @@protoc_insertion_point(struct:TransitRechargeAck) */
} TransitRechargeAck;

typedef PB_BYTES_ARRAY_T(18) TransitRechargeParam_aid_t;
typedef struct _TransitRechargeParam {
    TransitRechargeParam_aid_t aid;
/* @@protoc_insertion_point(struct:TransitRechargeParam) */
} TransitRechargeParam;

typedef PB_BYTES_ARRAY_T(18) TransitSetUseCityParam_aid_t;
typedef PB_BYTES_ARRAY_T(20) TransitSetUseCityParam_nfc_setting_t;
typedef struct _TransitSetUseCityParam {
    TransitSetUseCityParam_aid_t aid;
    char use_city_id[10];
    char use_city_name[30];
    TransitSetUseCityParam_nfc_setting_t nfc_setting;
/* @@protoc_insertion_point(struct:TransitSetUseCityParam) */
} TransitSetUseCityParam;

typedef struct _TransitList {
    pb_size_t infos_count;
    TransitInfo infos[5];
/* @@protoc_insertion_point(struct:TransitList) */
} TransitList;

/* Default values for struct fields */

/* Initializer values for message structs */
#define TransitCreateParam_init_default          {{0, {0}}, "", false, ""}
#define TransitCreateAck_init_default            {0}
#define TransitRechargeParam_init_default        {{0, {0}}}
#define TransitRechargeAck_init_default          {0}
#define TransitInfo_init_default                 {{0, {0}}, "", "", {0, {0}}}
#define TransitList_init_default                 {0, {TransitInfo_init_default, TransitInfo_init_default, TransitInfo_init_default, TransitInfo_init_default, TransitInfo_init_default}}
#define TransitSetUseCityParam_init_default      {{0, {0}}, "", "", {0, {0}}}
#define TransitCreateParam_init_zero             {{0, {0}}, "", false, ""}
#define TransitCreateAck_init_zero               {0}
#define TransitRechargeParam_init_zero           {{0, {0}}}
#define TransitRechargeAck_init_zero             {0}
#define TransitInfo_init_zero                    {{0, {0}}, "", "", {0, {0}}}
#define TransitList_init_zero                    {0, {TransitInfo_init_zero, TransitInfo_init_zero, TransitInfo_init_zero, TransitInfo_init_zero, TransitInfo_init_zero}}
#define TransitSetUseCityParam_init_zero         {{0, {0}}, "", "", {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define TransitCreateAck_code_tag                1
#define TransitCreateParam_aid_tag               1
#define TransitCreateParam_name_tag              2
#define TransitCreateParam_city_id_tag           3
#define TransitInfo_aid_tag                      1
#define TransitInfo_use_city_id_tag              2
#define TransitInfo_use_city_name_tag            3
#define TransitInfo_nfc_setting_tag              4
#define TransitRechargeAck_code_tag              1
#define TransitRechargeParam_aid_tag             1
#define TransitSetUseCityParam_aid_tag           1
#define TransitSetUseCityParam_use_city_id_tag   2
#define TransitSetUseCityParam_use_city_name_tag 3
#define TransitSetUseCityParam_nfc_setting_tag   4
#define TransitList_infos_tag                    1

/* Struct field encoding specification for nanopb */
extern const pb_field_t TransitCreateParam_fields[4];
extern const pb_field_t TransitCreateAck_fields[2];
extern const pb_field_t TransitRechargeParam_fields[2];
extern const pb_field_t TransitRechargeAck_fields[2];
extern const pb_field_t TransitInfo_fields[5];
extern const pb_field_t TransitList_fields[2];
extern const pb_field_t TransitSetUseCityParam_fields[5];

/* Maximum encoded size of messages (where known) */
#define TransitCreateParam_size                  54
#define TransitCreateAck_size                    11
#define TransitRechargeParam_size                20
#define TransitRechargeAck_size                  11
#define TransitInfo_size                         86
#define TransitList_size                         440
#define TransitSetUseCityParam_size              86

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define TRANSIT_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
