/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Fri Sep 07 17:30:48 2018. */

#include "Transit.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t TransitCreateParam_fields[4] = {
    PB_FIELD(  1, BYTES   , REQUIRED, STATIC  , FIRST, TransitCreateParam, aid, aid, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, TransitCreateParam, name, aid, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, STATIC  , OTHER, TransitCreateParam, city_id, name, 0),
    PB_LAST_FIELD
};

const pb_field_t TransitCreateAck_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, TransitCreateAck, code, code, 0),
    PB_LAST_FIELD
};

const pb_field_t TransitRechargeParam_fields[2] = {
    PB_FIELD(  1, BYTES   , REQUIRED, STATIC  , FIRST, TransitRechargeParam, aid, aid, 0),
    PB_LAST_FIELD
};

const pb_field_t TransitRechargeAck_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, TransitRechargeAck, code, code, 0),
    PB_LAST_FIELD
};

const pb_field_t TransitInfo_fields[5] = {
    PB_FIELD(  1, BYTES   , REQUIRED, STATIC  , FIRST, TransitInfo, aid, aid, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, TransitInfo, use_city_id, aid, 0),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC  , OTHER, TransitInfo, use_city_name, use_city_id, 0),
    PB_FIELD(  4, BYTES   , REQUIRED, STATIC  , OTHER, TransitInfo, nfc_setting, use_city_name, 0),
    PB_LAST_FIELD
};

const pb_field_t TransitList_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, TransitList, infos, infos, &TransitInfo_fields),
    PB_LAST_FIELD
};

const pb_field_t TransitSetUseCityParam_fields[5] = {
    PB_FIELD(  1, BYTES   , REQUIRED, STATIC  , FIRST, TransitSetUseCityParam, aid, aid, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, TransitSetUseCityParam, use_city_id, aid, 0),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC  , OTHER, TransitSetUseCityParam, use_city_name, use_city_id, 0),
    PB_FIELD(  4, BYTES   , REQUIRED, STATIC  , OTHER, TransitSetUseCityParam, nfc_setting, use_city_name, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(TransitList, infos[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_TransitCreateParam_TransitCreateAck_TransitRechargeParam_TransitRechargeAck_TransitInfo_TransitList_TransitSetUseCityParam)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(TransitList, infos[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_TransitCreateParam_TransitCreateAck_TransitRechargeParam_TransitRechargeAck_TransitInfo_TransitList_TransitSetUseCityParam)
#endif


/* @@protoc_insertion_point(eof) */
