/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Mon Apr 16 11:25:30 2018. */

#ifndef PB_WEATHER_PB_H_INCLUDED
#define PB_WEATHER_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _WeatherCityItem {
    char city_id[20];
    char city_name[40];
/* @@protoc_insertion_point(struct:WeatherCityItem) */
} WeatherCityItem;

typedef struct _WeatherForecastInfo_DailyInfo {
    int32_t date;
    float day_temp;
    int32_t day_type;
    float night_temp;
    int32_t night_type;
/* @@protoc_insertion_point(struct:WeatherForecastInfo_DailyInfo) */
} WeatherForecastInfo_DailyInfo;

typedef struct _WeatherGetForecastInfoParam {
    pb_size_t city_ids_count;
    char city_ids[5][20];
/* @@protoc_insertion_point(struct:WeatherGetForecastInfoParam) */
} WeatherGetForecastInfoParam;

typedef struct _WeatherGetInfoParam {
    pb_size_t city_ids_count;
    char city_ids[5][20];
/* @@protoc_insertion_point(struct:WeatherGetInfoParam) */
} WeatherGetInfoParam;

typedef struct _WeatherGetRealtimeInfoParam {
    pb_size_t city_ids_count;
    char city_ids[5][20];
/* @@protoc_insertion_point(struct:WeatherGetRealtimeInfoParam) */
} WeatherGetRealtimeInfoParam;

typedef struct _WeatherInfo_DailyInfo {
    int32_t date;
    bool has_realtime_temp;
    float realtime_temp;
    bool has_realtime_aqi;
    int32_t realtime_aqi;
    bool has_realtime_type;
    int32_t realtime_type;
    bool has_forecast_day_temp;
    float forecast_day_temp;
    bool has_forecast_day_type;
    int32_t forecast_day_type;
    bool has_forecast_night_temp;
    float forecast_night_temp;
    bool has_forecast_night_type;
    int32_t forecast_night_type;
/* @@protoc_insertion_point(struct:WeatherInfo_DailyInfo) */
} WeatherInfo_DailyInfo;

typedef struct _WeatherRealtimeInfo {
    char city_id[20];
    bool has_temp;
    float temp;
    bool has_aqi;
    int32_t aqi;
    bool has_type;
    int32_t type;
/* @@protoc_insertion_point(struct:WeatherRealtimeInfo) */
} WeatherRealtimeInfo;

typedef struct _WeatherCityList {
    pb_size_t city_items_count;
    WeatherCityItem city_items[5];
/* @@protoc_insertion_point(struct:WeatherCityList) */
} WeatherCityList;

typedef struct _WeatherForecastInfo {
    char city_id[20];
    pb_size_t daily_infos_count;
    WeatherForecastInfo_DailyInfo daily_infos[7];
/* @@protoc_insertion_point(struct:WeatherForecastInfo) */
} WeatherForecastInfo;

typedef struct _WeatherGetRealtimeInfoResult {
    pb_size_t infos_count;
    WeatherRealtimeInfo infos[5];
/* @@protoc_insertion_point(struct:WeatherGetRealtimeInfoResult) */
} WeatherGetRealtimeInfoResult;

typedef struct _WeatherInfo {
    char city_id[20];
    pb_size_t daily_infos_count;
    WeatherInfo_DailyInfo daily_infos[7];
/* @@protoc_insertion_point(struct:WeatherInfo) */
} WeatherInfo;

typedef struct _WeatherGetForecastInfoResult {
    pb_size_t infos_count;
    WeatherForecastInfo infos[5];
/* @@protoc_insertion_point(struct:WeatherGetForecastInfoResult) */
} WeatherGetForecastInfoResult;

typedef struct _WeatherGetInfoResult {
    pb_size_t infos_count;
    WeatherInfo infos[5];
/* @@protoc_insertion_point(struct:WeatherGetInfoResult) */
} WeatherGetInfoResult;

/* Default values for struct fields */

/* Initializer values for message structs */
#define WeatherCityItem_init_default             {"", ""}
#define WeatherCityList_init_default             {0, {WeatherCityItem_init_default, WeatherCityItem_init_default, WeatherCityItem_init_default, WeatherCityItem_init_default, WeatherCityItem_init_default}}
#define WeatherInfo_init_default                 {"", 0, {WeatherInfo_DailyInfo_init_default, WeatherInfo_DailyInfo_init_default, WeatherInfo_DailyInfo_init_default, WeatherInfo_DailyInfo_init_default, WeatherInfo_DailyInfo_init_default, WeatherInfo_DailyInfo_init_default, WeatherInfo_DailyInfo_init_default}}
#define WeatherInfo_DailyInfo_init_default       {0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define WeatherGetInfoParam_init_default         {0, {"", "", "", "", ""}}
#define WeatherGetInfoResult_init_default        {0, {WeatherInfo_init_default, WeatherInfo_init_default, WeatherInfo_init_default, WeatherInfo_init_default, WeatherInfo_init_default}}
#define WeatherGetRealtimeInfoParam_init_default {0, {"", "", "", "", ""}}
#define WeatherRealtimeInfo_init_default         {"", false, 0, false, 0, false, 0}
#define WeatherGetRealtimeInfoResult_init_default {0, {WeatherRealtimeInfo_init_default, WeatherRealtimeInfo_init_default, WeatherRealtimeInfo_init_default, WeatherRealtimeInfo_init_default, WeatherRealtimeInfo_init_default}}
#define WeatherGetForecastInfoParam_init_default {0, {"", "", "", "", ""}}
#define WeatherForecastInfo_init_default         {"", 0, {WeatherForecastInfo_DailyInfo_init_default, WeatherForecastInfo_DailyInfo_init_default, WeatherForecastInfo_DailyInfo_init_default, WeatherForecastInfo_DailyInfo_init_default, WeatherForecastInfo_DailyInfo_init_default, WeatherForecastInfo_DailyInfo_init_default, WeatherForecastInfo_DailyInfo_init_default}}
#define WeatherForecastInfo_DailyInfo_init_default {0, 0, 0, 0, 0}
#define WeatherGetForecastInfoResult_init_default {0, {WeatherForecastInfo_init_default, WeatherForecastInfo_init_default, WeatherForecastInfo_init_default, WeatherForecastInfo_init_default, WeatherForecastInfo_init_default}}
#define WeatherCityItem_init_zero                {"", ""}
#define WeatherCityList_init_zero                {0, {WeatherCityItem_init_zero, WeatherCityItem_init_zero, WeatherCityItem_init_zero, WeatherCityItem_init_zero, WeatherCityItem_init_zero}}
#define WeatherInfo_init_zero                    {"", 0, {WeatherInfo_DailyInfo_init_zero, WeatherInfo_DailyInfo_init_zero, WeatherInfo_DailyInfo_init_zero, WeatherInfo_DailyInfo_init_zero, WeatherInfo_DailyInfo_init_zero, WeatherInfo_DailyInfo_init_zero, WeatherInfo_DailyInfo_init_zero}}
#define WeatherInfo_DailyInfo_init_zero          {0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define WeatherGetInfoParam_init_zero            {0, {"", "", "", "", ""}}
#define WeatherGetInfoResult_init_zero           {0, {WeatherInfo_init_zero, WeatherInfo_init_zero, WeatherInfo_init_zero, WeatherInfo_init_zero, WeatherInfo_init_zero}}
#define WeatherGetRealtimeInfoParam_init_zero    {0, {"", "", "", "", ""}}
#define WeatherRealtimeInfo_init_zero            {"", false, 0, false, 0, false, 0}
#define WeatherGetRealtimeInfoResult_init_zero   {0, {WeatherRealtimeInfo_init_zero, WeatherRealtimeInfo_init_zero, WeatherRealtimeInfo_init_zero, WeatherRealtimeInfo_init_zero, WeatherRealtimeInfo_init_zero}}
#define WeatherGetForecastInfoParam_init_zero    {0, {"", "", "", "", ""}}
#define WeatherForecastInfo_init_zero            {"", 0, {WeatherForecastInfo_DailyInfo_init_zero, WeatherForecastInfo_DailyInfo_init_zero, WeatherForecastInfo_DailyInfo_init_zero, WeatherForecastInfo_DailyInfo_init_zero, WeatherForecastInfo_DailyInfo_init_zero, WeatherForecastInfo_DailyInfo_init_zero, WeatherForecastInfo_DailyInfo_init_zero}}
#define WeatherForecastInfo_DailyInfo_init_zero  {0, 0, 0, 0, 0}
#define WeatherGetForecastInfoResult_init_zero   {0, {WeatherForecastInfo_init_zero, WeatherForecastInfo_init_zero, WeatherForecastInfo_init_zero, WeatherForecastInfo_init_zero, WeatherForecastInfo_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define WeatherCityItem_city_id_tag              1
#define WeatherCityItem_city_name_tag            2
#define WeatherForecastInfo_DailyInfo_date_tag   1
#define WeatherForecastInfo_DailyInfo_day_temp_tag 2
#define WeatherForecastInfo_DailyInfo_day_type_tag 3
#define WeatherForecastInfo_DailyInfo_night_temp_tag 4
#define WeatherForecastInfo_DailyInfo_night_type_tag 5
#define WeatherGetForecastInfoParam_city_ids_tag 1
#define WeatherGetInfoParam_city_ids_tag         1
#define WeatherGetRealtimeInfoParam_city_ids_tag 1
#define WeatherInfo_DailyInfo_date_tag           1
#define WeatherInfo_DailyInfo_realtime_temp_tag  10
#define WeatherInfo_DailyInfo_realtime_aqi_tag   11
#define WeatherInfo_DailyInfo_realtime_type_tag  12
#define WeatherInfo_DailyInfo_forecast_day_temp_tag 30
#define WeatherInfo_DailyInfo_forecast_day_type_tag 31
#define WeatherInfo_DailyInfo_forecast_night_temp_tag 32
#define WeatherInfo_DailyInfo_forecast_night_type_tag 33
#define WeatherRealtimeInfo_city_id_tag          1
#define WeatherRealtimeInfo_temp_tag             2
#define WeatherRealtimeInfo_aqi_tag              3
#define WeatherRealtimeInfo_type_tag             4
#define WeatherCityList_city_items_tag           1
#define WeatherForecastInfo_city_id_tag          1
#define WeatherForecastInfo_daily_infos_tag      2
#define WeatherGetRealtimeInfoResult_infos_tag   1
#define WeatherInfo_city_id_tag                  1
#define WeatherInfo_daily_infos_tag              2
#define WeatherGetForecastInfoResult_infos_tag   1
#define WeatherGetInfoResult_infos_tag           1

/* Struct field encoding specification for nanopb */
extern const pb_field_t WeatherCityItem_fields[3];
extern const pb_field_t WeatherCityList_fields[2];
extern const pb_field_t WeatherInfo_fields[3];
extern const pb_field_t WeatherInfo_DailyInfo_fields[9];
extern const pb_field_t WeatherGetInfoParam_fields[2];
extern const pb_field_t WeatherGetInfoResult_fields[2];
extern const pb_field_t WeatherGetRealtimeInfoParam_fields[2];
extern const pb_field_t WeatherRealtimeInfo_fields[5];
extern const pb_field_t WeatherGetRealtimeInfoResult_fields[2];
extern const pb_field_t WeatherGetForecastInfoParam_fields[2];
extern const pb_field_t WeatherForecastInfo_fields[3];
extern const pb_field_t WeatherForecastInfo_DailyInfo_fields[6];
extern const pb_field_t WeatherGetForecastInfoResult_fields[2];

/* Maximum encoded size of messages (where known) */
#define WeatherCityItem_size                     64
#define WeatherCityList_size                     330
#define WeatherInfo_size                         554
#define WeatherInfo_DailyInfo_size               74
#define WeatherGetInfoParam_size                 110
#define WeatherGetInfoResult_size                2785
#define WeatherGetRealtimeInfoParam_size         110
#define WeatherRealtimeInfo_size                 49
#define WeatherGetRealtimeInfoResult_size        255
#define WeatherGetForecastInfoParam_size         110
#define WeatherForecastInfo_size                 337
#define WeatherForecastInfo_DailyInfo_size       43
#define WeatherGetForecastInfoResult_size        1700

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define WEATHER_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
