/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Mon Apr 16 11:25:30 2018. */

#include "Weather.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t WeatherCityItem_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, WeatherCityItem, city_id, city_id, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, WeatherCityItem, city_name, city_id, 0),
    PB_LAST_FIELD
};

const pb_field_t WeatherCityList_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, WeatherCityList, city_items, city_items, &WeatherCityItem_fields),
    PB_LAST_FIELD
};

const pb_field_t WeatherInfo_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, WeatherInfo, city_id, city_id, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, STATIC  , OTHER, WeatherInfo, daily_infos, city_id, &WeatherInfo_DailyInfo_fields),
    PB_LAST_FIELD
};

const pb_field_t WeatherInfo_DailyInfo_fields[9] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, WeatherInfo_DailyInfo, date, date, 0),
    PB_FIELD( 10, FLOAT   , OPTIONAL, STATIC  , OTHER, WeatherInfo_DailyInfo, realtime_temp, date, 0),
    PB_FIELD( 11, INT32   , OPTIONAL, STATIC  , OTHER, WeatherInfo_DailyInfo, realtime_aqi, realtime_temp, 0),
    PB_FIELD( 12, INT32   , OPTIONAL, STATIC  , OTHER, WeatherInfo_DailyInfo, realtime_type, realtime_aqi, 0),
    PB_FIELD( 30, FLOAT   , OPTIONAL, STATIC  , OTHER, WeatherInfo_DailyInfo, forecast_day_temp, realtime_type, 0),
    PB_FIELD( 31, INT32   , OPTIONAL, STATIC  , OTHER, WeatherInfo_DailyInfo, forecast_day_type, forecast_day_temp, 0),
    PB_FIELD( 32, FLOAT   , OPTIONAL, STATIC  , OTHER, WeatherInfo_DailyInfo, forecast_night_temp, forecast_day_type, 0),
    PB_FIELD( 33, INT32   , OPTIONAL, STATIC  , OTHER, WeatherInfo_DailyInfo, forecast_night_type, forecast_night_temp, 0),
    PB_LAST_FIELD
};

const pb_field_t WeatherGetInfoParam_fields[2] = {
    PB_FIELD(  1, STRING  , REPEATED, STATIC  , FIRST, WeatherGetInfoParam, city_ids, city_ids, 0),
    PB_LAST_FIELD
};

const pb_field_t WeatherGetInfoResult_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, WeatherGetInfoResult, infos, infos, &WeatherInfo_fields),
    PB_LAST_FIELD
};

const pb_field_t WeatherGetRealtimeInfoParam_fields[2] = {
    PB_FIELD(  1, STRING  , REPEATED, STATIC  , FIRST, WeatherGetRealtimeInfoParam, city_ids, city_ids, 0),
    PB_LAST_FIELD
};

const pb_field_t WeatherRealtimeInfo_fields[5] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, WeatherRealtimeInfo, city_id, city_id, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, WeatherRealtimeInfo, temp, city_id, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, WeatherRealtimeInfo, aqi, temp, 0),
    PB_FIELD(  4, INT32   , OPTIONAL, STATIC  , OTHER, WeatherRealtimeInfo, type, aqi, 0),
    PB_LAST_FIELD
};

const pb_field_t WeatherGetRealtimeInfoResult_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, WeatherGetRealtimeInfoResult, infos, infos, &WeatherRealtimeInfo_fields),
    PB_LAST_FIELD
};

const pb_field_t WeatherGetForecastInfoParam_fields[2] = {
    PB_FIELD(  1, STRING  , REPEATED, STATIC  , FIRST, WeatherGetForecastInfoParam, city_ids, city_ids, 0),
    PB_LAST_FIELD
};

const pb_field_t WeatherForecastInfo_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, WeatherForecastInfo, city_id, city_id, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, STATIC  , OTHER, WeatherForecastInfo, daily_infos, city_id, &WeatherForecastInfo_DailyInfo_fields),
    PB_LAST_FIELD
};

const pb_field_t WeatherForecastInfo_DailyInfo_fields[6] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, WeatherForecastInfo_DailyInfo, date, date, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, WeatherForecastInfo_DailyInfo, day_temp, date, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, WeatherForecastInfo_DailyInfo, day_type, day_temp, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, WeatherForecastInfo_DailyInfo, night_temp, day_type, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, WeatherForecastInfo_DailyInfo, night_type, night_temp, 0),
    PB_LAST_FIELD
};

const pb_field_t WeatherGetForecastInfoResult_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, WeatherGetForecastInfoResult, infos, infos, &WeatherForecastInfo_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(WeatherCityList, city_items[0]) < 65536 && pb_membersize(WeatherInfo, daily_infos[0]) < 65536 && pb_membersize(WeatherGetInfoResult, infos[0]) < 65536 && pb_membersize(WeatherGetRealtimeInfoResult, infos[0]) < 65536 && pb_membersize(WeatherForecastInfo, daily_infos[0]) < 65536 && pb_membersize(WeatherGetForecastInfoResult, infos[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_WeatherCityItem_WeatherCityList_WeatherInfo_WeatherInfo_DailyInfo_WeatherGetInfoParam_WeatherGetInfoResult_WeatherGetRealtimeInfoParam_WeatherRealtimeInfo_WeatherGetRealtimeInfoResult_WeatherGetForecastInfoParam_WeatherForecastInfo_WeatherForecastInfo_DailyInfo_WeatherGetForecastInfoResult)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(WeatherCityList, city_items[0]) < 256 && pb_membersize(WeatherInfo, daily_infos[0]) < 256 && pb_membersize(WeatherGetInfoResult, infos[0]) < 256 && pb_membersize(WeatherGetRealtimeInfoResult, infos[0]) < 256 && pb_membersize(WeatherForecastInfo, daily_infos[0]) < 256 && pb_membersize(WeatherGetForecastInfoResult, infos[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_WeatherCityItem_WeatherCityList_WeatherInfo_WeatherInfo_DailyInfo_WeatherGetInfoParam_WeatherGetInfoResult_WeatherGetRealtimeInfoParam_WeatherRealtimeInfo_WeatherGetRealtimeInfoResult_WeatherGetForecastInfoParam_WeatherForecastInfo_WeatherForecastInfo_DailyInfo_WeatherGetForecastInfoResult)
#endif


/* @@protoc_insertion_point(eof) */
